import { lazy, ComponentType } from "react";

export interface ChapterConfig {
  id: string;
  title: string;
  category: "fundamentals" | "intermediate" | "advanced";
  visualizer: React.LazyExoticComponent<ComponentType> | null;
  minigame: React.LazyExoticComponent<ComponentType> | null;
  hasCode: boolean;
}

// Dynamic imports for visualizers - mapped to chapter IDs
const visualizers: Record<string, React.LazyExoticComponent<ComponentType> | null> = {
  "01-big-o": lazy(() => import("@/components/chapters/ArrayVisualizerEnhanced")),
  "03-arrays": lazy(() => import("@/components/chapters/ArrayVisualizerEnhanced")),
  "05-linked-lists": lazy(() => import("@/components/chapters/LinkedListVisualizerEnhanced")),
  "06-stacks": lazy(() => import("@/components/chapters/StackVisualizerEnhanced")),
  "07-queues": lazy(() => import("@/components/chapters/QueueVisualizerEnhanced")),
  "04-strings": lazy(() => import("@/components/chapters/StringVisualizerEnhanced")),
  "09-hash-tables": lazy(() => import("@/components/chapters/HashTableVisualizerEnhanced")),
  "10-bst": lazy(() => import("@/components/chapters/BSTVisualizerEnhanced")),
  "11-heaps": lazy(() => import("@/components/chapters/HeapVisualizerEnhanced")),
  "12-graphs": lazy(() => import("@/components/chapters/GraphTraversalVisualizerEnhanced")),
  "13-dfs-bfs": lazy(() => import("@/components/chapters/GraphTraversalVisualizerEnhanced")),
  "16-tries": lazy(() => import("@/components/chapters/TrieVisualizerEnhanced")),
  "17-segment-trees": lazy(() => import("@/components/chapters/SegmentTreeVisualizerEnhanced")),
  "18-fenwick-trees": lazy(() => import("@/components/chapters/FenwickTreeVisualizerEnhanced")),
  "19-disjoint-sets": lazy(() => import("@/components/chapters/DisjointSetVisualizerEnhanced")),
  "08-searching": lazy(() => import("@/components/chapters/SearchingVisualizerEnhanced")),
  "14-shortest-paths": lazy(() => import("@/components/chapters/ShortestPathVisualizerEnhanced")),
  "15-mst": lazy(() => import("@/components/chapters/MSTVisualizerEnhanced")),
  "02-memory": lazy(() => import("@/components/chapters/MemoryVisualizerEnhanced")),
  "20-dp-fundamentals": lazy(() => import("@/components/chapters/DPVisualizerEnhanced")),
  "21-advanced-dp": lazy(() => import("@/components/chapters/DPVisualizerEnhanced")),
  "22-greedy-algorithms": lazy(() => import("@/components/chapters/GreedyVisualizerEnhanced")),
  "23-backtracking": lazy(() => import("@/components/chapters/BacktrackVisualizerEnhanced")),
  "24-bit-manipulation": lazy(() => import("@/components/chapters/BitManipVisualizerEnhanced")),
  "25-math-primes": lazy(() => import("@/components/chapters/MathVisualizerEnhanced")),
  "26-suffix-trees": lazy(() => import("@/components/chapters/SuffixTreeVisualizerEnhanced")),
  "27-kd-trees": lazy(() => import("@/components/chapters/KDTreeVisualizerEnhanced")),
  "28-bloom-filters": lazy(() => import("@/components/chapters/BloomFilterVisualizerEnhanced")),
  "29-network-flow": lazy(() => import("@/components/chapters/NetworkFlowVisualizerEnhanced")),
  "30-computational-geometry": lazy(() => import("@/components/chapters/GeometryVisualizerEnhanced")),
  // Book 3: Silicon Blueprint (Computer Architecture)
  "arch-01-binary": lazy(() => import("@/components/chapters/BinaryVisualizerEnhanced")),
  "arch-02-logic": lazy(() => import("@/components/chapters/LogicVisualizerEnhanced")),
  "arch-03-adder": lazy(() => import("@/components/chapters/ALUVisualizerEnhanced")),
  "arch-04-flipflop": lazy(() => import("@/components/chapters/MemoryVisualizerEnhanced")),
  "arch-05-registers": lazy(() => import("@/components/chapters/MemoryVisualizerEnhanced")),
  "arch-06-ram": lazy(() => import("@/components/chapters/MemoryVisualizerEnhanced")),
  "arch-07-cpu": null,
  "arch-08-instructions": null,
  "arch-09-pipelining": null,
  "arch-10-cache": null,
  "arch-11-assembly": null,
  "arch-12-virtual": null,
  // Book 2: Neural Network Atlas
  "ai-01-perceptron": lazy(() => import("@/components/chapters/PerceptronVisualizer")),
  "ai-02-activation": lazy(() => import("@/components/chapters/ActivationVisualizer")),
  "ai-03-backprop": null,
  "ai-04-gradient": null,
  "ai-05-learning-rate": null,
  "ai-06-mlp": null,
  "ai-07-cnn": null,
  "ai-08-rnn": null,
  "ai-09-transformers": null,
  "ai-10-gan": null,
  "ai-11-autoencoder": null,
  "ai-12-reinforcement": null,
  "ai-13-regularization": null,
  "ai-14-batch-norm": null,
  "ai-15-loss-functions": null,
  // Book 4: Cryptography
  "crypto-01-classical": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-02-symmetric": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-03-asymmetric": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-04-hashing": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-05-signatures": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-06-keyexchange": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-07-mac": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-08-protocols": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-09-pki": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-10-random": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-11-stream": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-12-ecc": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-13-passwords": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-14-zkp": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  "crypto-15-postquantum": lazy(() => import("@/components/chapters/CipherVisualizerEnhanced")),
  // Book 5: Quantum Computing
  "quantum-01-qubits": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-02-superposition": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-03-gates": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-04-entanglement": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-05-circuits": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-06-grover": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-07-shor": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-08-crypto": lazy(() => import("@/components/chapters/QubitVisualizerEnhanced")),
  "quantum-09-multi-qubit": null,
  "quantum-10-hardware": null,
  "quantum-11-error-correction": null,
  "quantum-12-variational": null,
  "quantum-13-ml": null,
  "quantum-14-walks": null,
  "quantum-15-protocols": null,
  // Book 6: Engine Room (Computer Science Engines)
  "engine-01-lexer": lazy(() => import("@/components/chapters/LexerVisualizerEnhanced")),
  "engine-02-parser": lazy(() => import("@/components/chapters/ParserVisualizerEnhanced")),
  "engine-03-vm": lazy(() => import("@/components/chapters/VMVisualizerEnhanced")),
  "engine-04-gc": lazy(() => import("@/components/chapters/GCVisualizerEnhanced")),
  "engine-05-allocator": lazy(() => import("@/components/chapters/AllocatorVisualizerEnhanced")),
  "engine-06-jit": lazy(() => import("@/components/chapters/JITVisualizerEnhanced")),
  "engine-07-types": lazy(() => import("@/components/chapters/TypeVisualizerEnhanced")),
  "engine-08-ir": lazy(() => import("@/components/chapters/IRVisualizerEnhanced")),
  "engine-09-codegen": lazy(() => import("@/components/chapters/CodegenVisualizerEnhanced")),
  "engine-10-linker": lazy(() => import("@/components/chapters/LinkerVisualizerEnhanced")),
  "engine-11-exceptions": lazy(() => import("@/components/chapters/ExceptionVisualizerEnhanced")),
  "engine-12-concurrency": lazy(() => import("@/components/chapters/ConcurrencyVisualizerEnhanced")),
  "engine-13-io": lazy(() => import("@/components/chapters/IOVisualizerEnhanced")),
  "engine-14-optimization": lazy(() => import("@/components/chapters/OptimizationVisualizerEnhanced")),
  "engine-15-profiling": lazy(() => import("@/components/chapters/ProfilingVisualizerEnhanced")),
};

// Dynamic imports for minigames - mapped to chapter IDs
const minigames: Record<string, React.LazyExoticComponent<ComponentType> | null> = {
  "01-big-o": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  "03-arrays": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  "05-linked-lists": lazy(() => import("@/components/minigames/LinkedListMinigameEnhanced")),
  "06-stacks": lazy(() => import("@/components/minigames/StackMinigameEnhanced")),
  "07-queues": lazy(() => import("@/components/minigames/QueueMinigameEnhanced")),
  "10-bst": lazy(() => import("@/components/minigames/BSTMinigameEnhanced")),
  "11-heaps": lazy(() => import("@/components/minigames/HeapMinigameEnhanced")),
  "02-memory": lazy(() => import("@/components/minigames/MemoryMinigameEnhanced")),
  "04-strings": lazy(() => import("@/components/minigames/StringMinigameEnhanced")),
  "08-searching": lazy(() => import("@/components/minigames/SearchingMinigameEnhanced")),
  "09-hash-tables": lazy(() => import("@/components/minigames/HashTableMinigameEnhanced")),
  "15-mst": lazy(() => import("@/components/minigames/GraphMinigameEnhanced")),
  "12-graphs": lazy(() => import("@/components/minigames/GraphMinigameEnhanced")),
  "13-dfs-bfs": lazy(() => import("@/components/minigames/GraphMinigameEnhanced")),
  "14-shortest-paths": lazy(() => import("@/components/minigames/GraphMinigameEnhanced")),
  "16-tries": lazy(() => import("@/components/minigames/TrieMinigameEnhanced")),
  "17-segment-trees": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  "18-fenwick-trees": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  "19-disjoint-sets": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  "20-dp-fundamentals": lazy(() => import("@/components/minigames/DPMinigameEnhanced")),
  "21-advanced-dp": lazy(() => import("@/components/minigames/DPMinigameEnhanced")),
  "22-greedy-algorithms": lazy(() => import("@/components/minigames/GreedyMinigameEnhanced")),
  "23-backtracking": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  "24-bit-manipulation": lazy(() => import("@/components/minigames/BitManipMinigameEnhanced")),
  "25-math-primes": lazy(() => import("@/components/minigames/MathMinigameEnhanced")),
  "26-suffix-trees": lazy(() => import("@/components/minigames/SuffixTreeMinigameEnhanced")),
  "27-kd-trees": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  "28-bloom-filters": lazy(() => import("@/components/minigames/HashTableMinigameEnhanced")),
  "29-network-flow": lazy(() => import("@/components/minigames/GraphMinigameEnhanced")),
  "30-computational-geometry": lazy(() => import("@/components/minigames/ArrayMinigameEnhanced")),
  // Book 3: Silicon Blueprint (Computer Architecture)
  "arch-01-binary": lazy(() => import("@/components/minigames/BinaryMinigameEnhanced")),
  "arch-02-logic": null,
  "arch-03-adder": null,
  "arch-04-flipflop": null,
  "arch-05-registers": null,
  "arch-06-ram": null,
  "arch-07-cpu": null,
  "arch-08-instructions": null,
  "arch-09-pipelining": null,
  "arch-10-cache": null,
  "arch-11-assembly": null,
  "arch-12-virtual": null,
  // Book 2: Neural Network Atlas
  "ai-01-perceptron": lazy(() => import("@/components/minigames/PerceptronMinigame")),
  "ai-02-activation": lazy(() => import("@/components/minigames/GradientDescentMinigame")),
  "ai-04-gradient": null,
  // Book 4: Cryptography
  "crypto-01-classical": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-02-symmetric": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-03-asymmetric": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-04-hashing": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-05-signatures": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-06-keyexchange": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-07-mac": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-08-protocols": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-09-pki": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-10-random": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-11-stream": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-12-ecc": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-13-passwords": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-14-zkp": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  "crypto-15-postquantum": lazy(() => import("@/components/minigames/CipherMinigameEnhanced")),
  // Book 5: Quantum Computing
  "quantum-01-qubits": lazy(() => import("@/components/minigames/QuantumGateMinigame")),
  "quantum-02-superposition": lazy(() => import("@/components/minigames/QuantumGateMinigame")),
  "quantum-03-gates": lazy(() => import("@/components/minigames/QuantumGateMinigame")),
  "quantum-04-entanglement": lazy(() => import("@/components/minigames/EntanglementMinigame")),
  "quantum-05-circuits": lazy(() => import("@/components/minigames/EntanglementMinigame")),
  "quantum-06-grover": lazy(() => import("@/components/minigames/QuantumGateMinigame")),
  "quantum-07-shor": lazy(() => import("@/components/minigames/QuantumGateMinigame")),
  "quantum-08-crypto": lazy(() => import("@/components/minigames/QuantumGateMinigame")),
  "quantum-09-multi-qubit": null,
  "quantum-10-hardware": null,
  "quantum-11-error-correction": null,
  "quantum-12-variational": null,
  "quantum-13-ml": null,
  "quantum-14-walks": null,
  "quantum-15-protocols": null,
  // Book 6: Engine Room (Computer Science Engines)
  "engine-01-lexer": lazy(() => import("@/components/minigames/LexerMinigameEnhanced")),
  "engine-02-parser": lazy(() => import("@/components/minigames/ParserMinigameEnhanced")),
  "engine-03-vm": lazy(() => import("@/components/minigames/VMMinigameEnhanced")),
  "engine-04-gc": lazy(() => import("@/components/minigames/GCMinigameEnhanced")),
  "engine-05-allocator": lazy(() => import("@/components/minigames/AllocatorMinigameEnhanced")),
  "engine-06-jit": lazy(() => import("@/components/minigames/JITMinigameEnhanced")),
  "engine-07-types": lazy(() => import("@/components/minigames/TypeMinigameEnhanced")),
  "engine-08-ir": lazy(() => import("@/components/minigames/IRMinigameEnhanced")),
  "engine-09-codegen": lazy(() => import("@/components/minigames/CodegenMinigameEnhanced")),
  "engine-10-linker": lazy(() => import("@/components/minigames/LinkerMinigameEnhanced")),
  "engine-11-exceptions": lazy(() => import("@/components/minigames/ExceptionMinigameEnhanced")),
  "engine-12-concurrency": lazy(() => import("@/components/minigames/ConcurrencyMinigameEnhanced")),
  "engine-13-io": lazy(() => import("@/components/minigames/IOMinigameEnhanced")),
  "engine-14-optimization": lazy(() => import("@/components/minigames/OptimizationMinigameEnhanced")),
  "engine-15-profiling": lazy(() => import("@/components/minigames/ProfilingMinigameEnhanced")),
};

export function getChapterConfig(id: string): ChapterConfig {
  const chapterMap: Record<string, Omit<ChapterConfig, "id" >> = {
    "01-big-o": {
      title: "Big O Notation",
      category: "fundamentals",
      visualizer: visualizers["01-big-o"] || null,
      minigame: minigames["01-big-o"] || null,
      hasCode: true,
    },
    "02-memory": {
      title: "Memory Management",
      category: "fundamentals",
      visualizer: visualizers["02-memory"] || null,
      minigame: minigames["02-memory"] || null,
      hasCode: true,
    },
    "03-arrays": {
      title: "Arrays & Operations",
      category: "fundamentals",
      visualizer: visualizers["03-arrays"] || null,
      minigame: minigames["03-arrays"] || null,
      hasCode: true,
    },
    "04-strings": {
      title: "Strings",
      category: "fundamentals",
      visualizer: visualizers["04-strings"] || null,
      minigame: minigames["04-strings"] || null,
      hasCode: true,
    },
    "05-linked-lists": {
      title: "Linked Lists",
      category: "fundamentals",
      visualizer: visualizers["05-linked-lists"] || null,
      minigame: minigames["05-linked-lists"] || null,
      hasCode: true,
    },
    "06-stacks": {
      title: "Stacks",
      category: "fundamentals",
      visualizer: visualizers["06-stacks"] || null,
      minigame: minigames["06-stacks"] || null,
      hasCode: true,
    },
    "07-queues": {
      title: "Queues",
      category: "fundamentals",
      visualizer: visualizers["07-queues"] || null,
      minigame: minigames["07-queues"] || null,
      hasCode: true,
    },
    "08-searching": {
      title: "Searching Algorithms",
      category: "advanced",
      visualizer: visualizers["08-searching"] || null,
      minigame: minigames["08-searching"] || null,
      hasCode: true,
    },
    "09-hash-tables": {
      title: "Hash Tables",
      category: "intermediate",
      visualizer: visualizers["09-hash-tables"] || null,
      minigame: minigames["09-hash-tables"] || null,
      hasCode: true,
    },
    "10-bst": {
      title: "Binary Search Trees",
      category: "intermediate",
      visualizer: visualizers["10-bst"] || null,
      minigame: minigames["10-bst"] || null,
      hasCode: true,
    },
    "11-heaps": {
      title: "Heaps",
      category: "intermediate",
      visualizer: visualizers["11-heaps"] || null,
      minigame: minigames["11-heaps"] || null,
      hasCode: true,
    },
    "12-graphs": {
      title: "Graph Fundamentals",
      category: "intermediate",
      visualizer: visualizers["12-graphs"] || null,
      minigame: minigames["12-graphs"] || null,
      hasCode: true,
    },
    "13-dfs-bfs": {
      title: "DFS & BFS Advanced",
      category: "intermediate",
      visualizer: visualizers["13-dfs-bfs"] || null,
      minigame: minigames["13-dfs-bfs"] || null,
      hasCode: true,
    },
    "14-shortest-paths": {
      title: "Shortest Paths",
      category: "advanced",
      visualizer: visualizers["14-shortest-paths"] || null,
      minigame: minigames["14-shortest-paths"] || null,
      hasCode: true,
    },
    "15-mst": {
      title: "Minimum Spanning Tree",
      category: "advanced",
      visualizer: visualizers["15-mst"] || null,
      minigame: minigames["15-mst"] || null,
      hasCode: true,
    },
    "16-tries": {
      title: "Tries (Prefix Trees)",
      category: "advanced",
      visualizer: visualizers["16-tries"] || null,
      minigame: minigames["16-tries"] || null,
      hasCode: true,
    },
    "17-segment-trees": {
      title: "Segment Trees",
      category: "advanced",
      visualizer: visualizers["17-segment-trees"] || null,
      minigame: minigames["17-segment-trees"] || null,
      hasCode: true,
    },
    "18-fenwick-trees": {
      title: "Fenwick Trees",
      category: "advanced",
      visualizer: visualizers["18-fenwick-trees"] || null,
      minigame: minigames["18-fenwick-trees"] || null,
      hasCode: true,
    },
    "19-disjoint-sets": {
      title: "Disjoint Set Union (Union-Find)",
      category: "advanced",
      visualizer: visualizers["19-disjoint-sets"] || null,
      minigame: minigames["19-disjoint-sets"] || null,
      hasCode: true,
    },
    "20-dp-fundamentals": {
      title: "DP Fundamentals",
      category: "advanced",
      visualizer: visualizers["20-dp-fundamentals"] || null,
      minigame: minigames["20-dp-fundamentals"] || null,
      hasCode: true,
    },
    "21-advanced-dp": {
      title: "Advanced DP",
      category: "advanced",
      visualizer: visualizers["21-advanced-dp"] || null,
      minigame: minigames["21-advanced-dp"] || null,
      hasCode: true,
    },
    "22-greedy": {
      title: "Greedy Algorithms",
      category: "advanced",
      visualizer: visualizers["22-greedy-algorithms"] || null,
      minigame: minigames["22-greedy-algorithms"] || null,
      hasCode: true,
    },
    "23-backtracking": {
      title: "Backtracking",
      category: "advanced",
      visualizer: visualizers["23-backtracking"] || null,
      minigame: minigames["23-backtracking"] || null,
      hasCode: true,
    },
    "24-bit-manipulation": {
      title: "Bit Manipulation",
      category: "advanced",
      visualizer: visualizers["24-bit-manipulation"] || null,
      minigame: minigames["24-bit-manipulation"] || null,
      hasCode: true,
    },
    "25-math-primes": {
      title: "Math & Primes",
      category: "advanced",
      visualizer: visualizers["25-math-primes"] || null,
      minigame: minigames["25-math-primes"] || null,
      hasCode: true,
    },
    "26-suffix-trees": {
      title: "Suffix Trees",
      category: "advanced",
      visualizer: visualizers["26-suffix-trees"] || null,
      minigame: minigames["26-suffix-trees"] || null,
      hasCode: true,
    },
    "27-kd-trees": {
      title: "K-D Trees",
      category: "advanced",
      visualizer: visualizers["27-kd-trees"] || null,
      minigame: minigames["27-kd-trees"] || null,
      hasCode: true,
    },
    "28-bloom-filters": {
      title: "Bloom Filters",
      category: "advanced",
      visualizer: visualizers["28-bloom-filters"] || null,
      minigame: minigames["28-bloom-filters"] || null,
      hasCode: true,
    },
    "29-network-flow": {
      title: "Network Flow",
      category: "advanced",
      visualizer: visualizers["29-network-flow"] || null,
      minigame: minigames["29-network-flow"] || null,
      hasCode: true,
    },
    "30-computational-geometry": {
      title: "Computational Geometry",
      category: "advanced",
      visualizer: visualizers["30-computational-geometry"] || null,
      minigame: minigames["30-computational-geometry"] || null,
      hasCode: true,
    },
    // Book 3: Silicon Blueprint (Computer Architecture)
    "arch-01-binary": {
      title: "Binary & Number Systems",
      category: "fundamentals",
      visualizer: visualizers["arch-01-binary"] || null,
      minigame: minigames["arch-01-binary"] || null,
      hasCode: true,
    },
    "arch-02-logic": {
      title: "Logic Gates",
      category: "fundamentals",
      visualizer: visualizers["arch-02-logic"] || null,
      minigame: minigames["arch-02-logic"] || null,
      hasCode: true,
    },
    "arch-03-adder": {
      title: "Adders & ALU",
      category: "intermediate",
      visualizer: visualizers["arch-03-adder"] || null,
      minigame: minigames["arch-03-adder"] || null,
      hasCode: true,
    },
    "arch-04-flipflop": {
      title: "Flip-Flops & Memory",
      category: "intermediate",
      visualizer: visualizers["arch-04-flipflop"] || null,
      minigame: minigames["arch-04-flipflop"] || null,
      hasCode: true,
    },
    "arch-05-registers": {
      title: "Registers & Counters",
      category: "intermediate",
      visualizer: visualizers["arch-05-registers"] || null,
      minigame: minigames["arch-05-registers"] || null,
      hasCode: true,
    },
    "arch-06-ram": {
      title: "RAM Architecture",
      category: "intermediate",
      visualizer: visualizers["arch-06-ram"] || null,
      minigame: minigames["arch-06-ram"] || null,
      hasCode: true,
    },
    "arch-07-cpu": {
      title: "CPU Architecture",
      category: "advanced",
      visualizer: visualizers["arch-07-cpu"] || null,
      minigame: minigames["arch-07-cpu"] || null,
      hasCode: true,
    },
    "arch-08-instructions": {
      title: "Instruction Cycle",
      category: "advanced",
      visualizer: visualizers["arch-08-instructions"] || null,
      minigame: minigames["arch-08-instructions"] || null,
      hasCode: true,
    },
    "arch-09-pipelining": {
      title: "Pipelining",
      category: "advanced",
      visualizer: visualizers["arch-09-pipelining"] || null,
      minigame: minigames["arch-09-pipelining"] || null,
      hasCode: true,
    },
    "arch-10-cache": {
      title: "Cache Memory",
      category: "advanced",
      visualizer: visualizers["arch-10-cache"] || null,
      minigame: minigames["arch-10-cache"] || null,
      hasCode: true,
    },
    "arch-11-assembly": {
      title: "Assembly Language",
      category: "advanced",
      visualizer: visualizers["arch-11-assembly"] || null,
      minigame: minigames["arch-11-assembly"] || null,
      hasCode: true,
    },
    "arch-12-virtual": {
      title: "Virtual Memory",
      category: "advanced",
      visualizer: visualizers["arch-12-virtual"] || null,
      minigame: minigames["arch-12-virtual"] || null,
      hasCode: true,
    },
    // Book 4: Cryptography
    "crypto-01-classical": {
      title: "Classical Ciphers",
      category: "fundamentals",
      visualizer: visualizers["crypto-01-classical"] || null,
      minigame: minigames["crypto-01-classical"] || null,
      hasCode: true,
    },
    "crypto-02-symmetric": {
      title: "Symmetric Encryption",
      category: "fundamentals",
      visualizer: visualizers["crypto-02-symmetric"] || null,
      minigame: minigames["crypto-02-symmetric"] || null,
      hasCode: true,
    },
    "crypto-03-asymmetric": {
      title: "Public Key Cryptography",
      category: "intermediate",
      visualizer: visualizers["crypto-03-asymmetric"] || null,
      minigame: minigames["crypto-03-asymmetric"] || null,
      hasCode: true,
    },
    "crypto-04-hashing": {
      title: "Hash Functions",
      category: "intermediate",
      visualizer: visualizers["crypto-04-hashing"] || null,
      minigame: minigames["crypto-04-hashing"] || null,
      hasCode: true,
    },
    "crypto-05-signatures": {
      title: "Digital Signatures",
      category: "advanced",
      visualizer: visualizers["crypto-05-signatures"] || null,
      minigame: minigames["crypto-05-signatures"] || null,
      hasCode: true,
    },
    "crypto-06-keyexchange": {
      title: "Key Exchange",
      category: "intermediate",
      visualizer: visualizers["crypto-06-keyexchange"] || null,
      minigame: minigames["crypto-06-keyexchange"] || null,
      hasCode: true,
    },
    "crypto-07-mac": {
      title: "Message Authentication Codes",
      category: "intermediate",
      visualizer: visualizers["crypto-07-mac"] || null,
      minigame: minigames["crypto-07-mac"] || null,
      hasCode: true,
    },
    "crypto-08-protocols": {
      title: "Cryptographic Protocols",
      category: "intermediate",
      visualizer: visualizers["crypto-08-protocols"] || null,
      minigame: minigames["crypto-08-protocols"] || null,
      hasCode: true,
    },
    "crypto-09-pki": {
      title: "Public Key Infrastructure",
      category: "intermediate",
      visualizer: visualizers["crypto-09-pki"] || null,
      minigame: minigames["crypto-09-pki"] || null,
      hasCode: true,
    },
    "crypto-10-random": {
      title: "Random Number Generation",
      category: "fundamentals",
      visualizer: visualizers["crypto-10-random"] || null,
      minigame: minigames["crypto-10-random"] || null,
      hasCode: true,
    },
    "crypto-11-stream": {
      title: "Stream Ciphers",
      category: "intermediate",
      visualizer: visualizers["crypto-11-stream"] || null,
      minigame: minigames["crypto-11-stream"] || null,
      hasCode: true,
    },
    "crypto-12-ecc": {
      title: "Elliptic Curve Cryptography",
      category: "advanced",
      visualizer: visualizers["crypto-12-ecc"] || null,
      minigame: minigames["crypto-12-ecc"] || null,
      hasCode: true,
    },
    "crypto-13-passwords": {
      title: "Password Hashing",
      category: "intermediate",
      visualizer: visualizers["crypto-13-passwords"] || null,
      minigame: minigames["crypto-13-passwords"] || null,
      hasCode: true,
    },
    "crypto-14-zkp": {
      title: "Zero-Knowledge Proofs",
      category: "advanced",
      visualizer: visualizers["crypto-14-zkp"] || null,
      minigame: minigames["crypto-14-zkp"] || null,
      hasCode: true,
    },
    "crypto-15-postquantum": {
      title: "Post-Quantum Cryptography",
      category: "advanced",
      visualizer: visualizers["crypto-15-postquantum"] || null,
      minigame: minigames["crypto-15-postquantum"] || null,
      hasCode: true,
    },
    // Book 5: Quantum Computing
    "01-qubits": {
      title: "Qubits: The Quantum Bit",
      category: "fundamentals",
      visualizer: visualizers["01-qubits"] || null,
      minigame: minigames["01-qubits"] || null,
      hasCode: true,
    },
    "02-superposition": {
      title: "Superposition & Interference",
      category: "fundamentals",
      visualizer: visualizers["02-superposition"] || null,
      minigame: minigames["02-superposition"] || null,
      hasCode: true,
    },
    "03-single-qubit-gates": {
      title: "Single-Qubit Gates",
      category: "fundamentals",
      visualizer: visualizers["03-single-qubit-gates"] || null,
      minigame: minigames["03-single-qubit-gates"] || null,
      hasCode: true,
    },
    "04-entanglement": {
      title: "Entanglement",
      category: "fundamentals",
      visualizer: visualizers["04-entanglement"] || null,
      minigame: minigames["04-entanglement"] || null,
      hasCode: true,
    },
    "05-quantum-circuits": {
      title: "Quantum Circuits",
      category: "intermediate",
      visualizer: visualizers["05-quantum-circuits"] || null,
      minigame: minigames["05-quantum-circuits"] || null,
      hasCode: true,
    },
    "06-grover-algorithm": {
      title: "Grover's Search Algorithm",
      category: "advanced",
      visualizer: visualizers["06-grover-algorithm"] || null,
      minigame: minigames["06-grover-algorithm"] || null,
      hasCode: true,
    },
    "07-shor-algorithm": {
      title: "Shor's Factoring Algorithm",
      category: "advanced",
      visualizer: visualizers["07-shor-algorithm"] || null,
      minigame: minigames["07-shor-algorithm"] || null,
      hasCode: true,
    },
    "08-quantum-cryptography": {
      title: "Quantum Cryptography",
      category: "intermediate",
      visualizer: visualizers["08-quantum-cryptography"] || null,
      minigame: minigames["08-quantum-cryptography"] || null,
      hasCode: true,
    },
    "09-multi-qubit-gates": {
      title: "Multi-Qubit Gates",
      category: "intermediate",
      visualizer: visualizers["09-multi-qubit-gates"] || null,
      minigame: minigames["09-multi-qubit-gates"] || null,
      hasCode: true,
    },
    "10-quantum-hardware": {
      title: "Quantum Hardware & Decoherence",
      category: "advanced",
      visualizer: visualizers["10-quantum-hardware"] || null,
      minigame: minigames["10-quantum-hardware"] || null,
      hasCode: true,
    },
    "11-quantum-error-correction": {
      title: "Quantum Error Correction",
      category: "advanced",
      visualizer: visualizers["11-quantum-error-correction"] || null,
      minigame: minigames["11-quantum-error-correction"] || null,
      hasCode: true,
    },
    "12-variational-quantum-algorithms": {
      title: "Variational Quantum Algorithms",
      category: "advanced",
      visualizer: visualizers["12-variational-quantum-algorithms"] || null,
      minigame: minigames["12-variational-quantum-algorithms"] || null,
      hasCode: true,
    },
    "13-quantum-machine-learning": {
      title: "Quantum Machine Learning",
      category: "intermediate",
      visualizer: visualizers["13-quantum-machine-learning"] || null,
      minigame: minigames["13-quantum-machine-learning"] || null,
      hasCode: true,
    },
    "14-quantum-walks": {
      title: "Quantum Walks",
      category: "advanced",
      visualizer: visualizers["14-quantum-walks"] || null,
      minigame: minigames["14-quantum-walks"] || null,
      hasCode: true,
    },
    "15-advanced-protocols": {
      title: "Advanced Quantum Protocols",
      category: "intermediate",
      visualizer: visualizers["15-advanced-protocols"] || null,
      minigame: minigames["15-advanced-protocols"] || null,
      hasCode: true,
    },
    // Book 6: Engine Room (Computer Science Engines)
    "engine-01-lexer": {
      title: "Lexical Analysis & Tokenization",
      category: "intermediate",
      visualizer: visualizers["engine-01-lexer"] || null,
      minigame: minigames["engine-01-lexer"] || null,
      hasCode: true,
    },
    "engine-02-parser": {
      title: "Parsing & Abstract Syntax Trees",
      category: "intermediate",
      visualizer: visualizers["engine-02-parser"] || null,
      minigame: minigames["engine-02-parser"] || null,
      hasCode: true,
    },
    "engine-03-vm": {
      title: "Virtual Machines & Bytecode",
      category: "intermediate",
      visualizer: visualizers["engine-03-vm"] || null,
      minigame: minigames["engine-03-vm"] || null,
      hasCode: true,
    },
    "engine-04-gc": {
      title: "Garbage Collection",
      category: "advanced",
      visualizer: visualizers["engine-04-gc"] || null,
      minigame: minigames["engine-04-gc"] || null,
      hasCode: true,
    },
    "engine-05-allocator": {
      title: "Memory Allocation Strategies",
      category: "advanced",
      visualizer: visualizers["engine-05-allocator"] || null,
      minigame: minigames["engine-05-allocator"] || null,
      hasCode: true,
    },
    "engine-06-jit": {
      title: "JIT Compilation",
      category: "advanced",
      visualizer: visualizers["engine-06-jit"] || null,
      minigame: minigames["engine-06-jit"] || null,
      hasCode: true,
    },
    "engine-07-types": {
      title: "Type Systems & Type Checking",
      category: "intermediate",
      visualizer: visualizers["engine-07-types"] || null,
      minigame: minigames["engine-07-types"] || null,
      hasCode: true,
    },
    "engine-08-ir": {
      title: "Intermediate Representations",
      category: "intermediate",
      visualizer: visualizers["engine-08-ir"] || null,
      minigame: minigames["engine-08-ir"] || null,
      hasCode: true,
    },
    "engine-09-codegen": {
      title: "Code Generation & Instruction Selection",
      category: "advanced",
      visualizer: visualizers["engine-09-codegen"] || null,
      minigame: minigames["engine-09-codegen"] || null,
      hasCode: true,
    },
    "engine-10-linker": {
      title: "Linkers & Loaders",
      category: "advanced",
      visualizer: visualizers["engine-10-linker"] || null,
      minigame: minigames["engine-10-linker"] || null,
      hasCode: true,
    },
    "engine-11-exceptions": {
      title: "Exception Handling & Stack Unwinding",
      category: "advanced",
      visualizer: visualizers["engine-11-exceptions"] || null,
      minigame: minigames["engine-11-exceptions"] || null,
      hasCode: true,
    },
    "engine-12-concurrency": {
      title: "Concurrency & Threading",
      category: "advanced",
      visualizer: visualizers["engine-12-concurrency"] || null,
      minigame: minigames["engine-12-concurrency"] || null,
      hasCode: true,
    },
    "engine-13-io": {
      title: "I/O Systems & Event Loops",
      category: "advanced",
      visualizer: visualizers["engine-13-io"] || null,
      minigame: minigames["engine-13-io"] || null,
      hasCode: true,
    },
    "engine-14-optimization": {
      title: "Optimization Passes",
      category: "advanced",
      visualizer: visualizers["engine-14-optimization"] || null,
      minigame: minigames["engine-14-optimization"] || null,
      hasCode: true,
    },
    "engine-15-profiling": {
      title: "Profiling & Performance Analysis",
      category: "advanced",
      visualizer: visualizers["engine-15-profiling"] || null,
      minigame: minigames["engine-15-profiling"] || null,
      hasCode: true,
    },
  };

  const config = chapterMap[id] || {
    title: "Unknown Chapter",
    category: "fundamentals",
    visualizer: null,
    minigame: null,
    hasCode: false,
  };

  return { id, ...config };
}

export async function loadChapterData(bookId: string, chapterId: string) {
  try {
    // Use fetch instead of dynamic import for Turbopack compatibility
    const response = await fetch(`/content/${bookId}/${chapterId}.json`);
    if (!response.ok) return null;
    return await response.json();
  } catch {
    return null;
  }
}
