"use client";

import React from "react";
import { motion } from "framer-motion";
import { useState, useEffect, useCallback } from "react";
import { Play, Pause, SkipBack, SkipForward, RotateCcw, ChevronLeft, ChevronRight, Filter, HelpCircle } from "lucide-react";
import { useTimeline, useCodeHighlight } from "@/lib/engine/store";

interface Step { step: number; title: string; description: string; codeLines: number[]; bitArray: boolean[]; items: string[]; queryItem: string | null; queryResult: "maybe" | "no" | null; hashFunctions: number; falsePositiveRate: number; explanation: string; theoryConnection: string; complexity: string; }

const speeds = [{ label: "0.5x", value: 0.5 }, { label: "1x", value: 1 }, { label: "1.5x", value: 1.5 }, { label: "2x", value: 2 }, { label: "3x", value: 3 }];

const codeLines = ["// Bloom Filter - Probabilistic data structure", "class BloomFilter {", "  constructor(size, hashCount) {", "    this.bits = new Array(size).fill(false);", "    this.size = size;", "    this.hashCount = hashCount;", "  }", "", "  add(item) {", "    for (let i = 0; i < this.hashCount; i++) {", "      const index = hash(item, i) % this.size;", "      this.bits[index] = true;", "    }", "  }", "", "  mightContain(item) {", "    for (let i = 0; i < this.hashCount; i++) {", "      const index = hash(item, i) % this.size;", "      if (!this.bits[index]) return false;", "    }", "    return true;  // Maybe (false positive possible)", "  }", "}", "", "// False positive probability: (1 - e^(-kn/m))^k", "// m = bits, n = items, k = hash functions"];

const hash = (s: string, seed: number): number => { let h = seed; for (let i = 0; i < s.length; i++) { h = ((h << 5) - h) + s.charCodeAt(i); h |= 0; } return Math.abs(h); };

const generateSteps = (): Step[] => [
  { step: 0, title: "Bloom Filters", description: "Probabilistic data structure for membership testing. Space-efficient but allows false positives.", codeLines: [1, 2, 3], bitArray: Array(16).fill(false), items: [], queryItem: null, queryResult: null, hashFunctions: 3, falsePositiveRate: 0, explanation: "Bloom filter answers: 'Is item possibly in set?' (maybe) or 'Is item definitely not in set?' (no). Uses bit array and multiple hash functions. Never false negatives, but may have false positives. Trade space for accuracy.", theoryConnection: "Invented by Burton Bloom (1970). Used in: databases (checking existence before disk read), web caching, Bitcoin (SPV clients), spell checkers, network routers. Google Bigtable, Apache Cassandra use bloom filters.", complexity: "Space: O(m) bits where m << n (items). Insert: O(k) hash computations. Query: O(k). k = number of hash functions." },
  { step: 1, title: "Initialize Empty Filter", description: "Create bit array of size m, all set to 0 (false).", codeLines: [3, 4], bitArray: Array(16).fill(false), items: [], queryItem: null, queryResult: null, hashFunctions: 3, falsePositiveRate: 0, explanation: "Start with 16-bit array (small for visualization). All bits 0. We'll use k=3 hash functions. Real bloom filters use much larger arrays (millions of bits) and more hash functions for better accuracy.", theoryConnection: "Bit array is compact: 1 million bits = 125KB. Can represent set membership for millions of items. Optimal k = (m/n) × ln(2). False positive rate p ≈ (0.6185)^(m/n). For 1% FP rate, need m ≈ 9.6n bits.", complexity: "Initialization: O(m) to zero memory. Negligible compared to operations." },
  { step: 2, title: "Add Item: 'apple'", description: "Compute 3 hash values, set corresponding bits to 1.", codeLines: [9, 10, 11, 12], bitArray: [true, false, false, true, false, false, true, false, false, false, false, false, false, false, false, false], items: ["apple"], queryItem: null, queryResult: null, hashFunctions: 3, falsePositiveRate: 0, explanation: "hash('apple', 0) % 16 = 0, hash('apple', 1) % 16 = 3, hash('apple', 2) % 16 = 6. Set bits 0, 3, 6 to 1. Now filter 'contains' apple (and anything else that hashes to these positions).", theoryConnection: "Multiple hash functions reduce collision probability. With k=3, item affects 3 random positions. Probability all 3 collide with existing items is small but non-zero. This is the false positive source.", complexity: "Insert: O(k) hash computations. Each hash O(1) on string length." },
  { step: 3, title: "Add Item: 'banana'", description: "Compute hashes for 'banana', set bits (may overlap).", codeLines: [9, 10, 11, 12], bitArray: [true, true, false, true, false, true, true, false, false, true, false, false, false, false, false, false], items: ["apple", "banana"], queryItem: null, queryResult: null, hashFunctions: 3, falsePositiveRate: 0, explanation: "hash('banana', 0) = 1, hash('banana', 1) = 5, hash('banana', 2) = 9. Set bits 1, 5, 9. Note: no overlap with apple's bits (0, 3, 6). Bit 6 stays 1 from apple only. If overlap occurred, bit stays 1 (no change).", theoryConnection: "No deletion in basic bloom filter (can't unset bits - might affect other items). Counting bloom filters use counters instead of bits to enable removal. Trade-off: more space per entry.", complexity: "Still O(k). Overlaps don't cost extra." },
  { step: 4, title: "Add Item: 'cherry'", description: "More items increase bit density, raising false positive risk.", codeLines: [9, 10, 11, 12], bitArray: [true, true, true, true, true, true, true, true, false, true, false, false, false, false, false, false], items: ["apple", "banana", "cherry"], queryItem: null, queryResult: null, hashFunctions: 3, falsePositiveRate: 0.02, explanation: "hash('cherry') → bits 2, 4, 7. Now bits 0-7 mostly filled. 8/16 = 50% occupancy. False positive rate rises as bits fill. Current theoretical FP rate: ~2% for this configuration.", theoryConnection: "FP probability = (1 - e^(-kn/m))^k. With n=3, m=16, k=3: FP ≈ 2%. To maintain low FP, need m >> n. Rule of thumb: 10 bits per item for 1% FP rate. Google uses billions of bits in production.", complexity: "Query time still O(k) regardless of bit density." },
  { step: 5, title: "Query: 'apple' (Member)", description: "Check all 3 hash positions. All set → 'maybe' in set.", codeLines: [16, 17, 18, 19], bitArray: [true, true, true, true, true, true, true, true, false, true, false, false, false, false, false, false], items: ["apple", "banana", "cherry"], queryItem: "apple", queryResult: "maybe", hashFunctions: 3, falsePositiveRate: 0.02, explanation: "Query 'apple': hash positions 0, 3, 6. All are 1. Return 'maybe present'. It's definitely in set (we added it). But we can't be 100% sure - could be false positive if some other item(s) set these bits.", theoryConnection: "True positive (correct). Bits were set by 'apple' itself. No false negative possible: if item was added, all its hash positions are set. Query will always find them set. Guaranteed no false negatives.", complexity: "Query: O(k). k independent of n (items)." },
  { step: 6, title: "Query: 'grape' (Not Member)", description: "At least one hash position is 0 → definitely not in set.", codeLines: [16, 17, 18, 19], bitArray: [true, true, true, true, true, true, true, true, false, true, false, false, false, false, false, false], items: ["apple", "banana", "cherry"], queryItem: "grape", queryResult: "no", hashFunctions: 3, falsePositiveRate: 0.02, explanation: "Query 'grape': Suppose hashes to positions 8, 10, 12. Bit 8 = 0 (unset). Immediately return 'definitely not present'. One zero bit is enough to confirm absence. This is the power of bloom filters - fast negative checks.", theoryConnection: "Definitely not in set = guaranteed correct. Used to avoid expensive lookups. Example: database checks bloom filter before disk read. If 'no', skip disk entirely. If 'maybe', check disk (might be FP). Saves disk I/O for non-existent keys.", complexity: "Early termination possible. Average less than k checks." },
  { step: 7, title: "Query: 'date' (False Positive Candidate)", description: "All 3 positions happen to be 1 → false positive!", codeLines: [16, 17, 18, 19], bitArray: [true, true, true, true, true, true, true, true, false, true, false, false, false, false, false, false], items: ["apple", "banana", "cherry"], queryItem: "date", queryResult: "maybe", hashFunctions: 3, falsePositiveRate: 0.02, explanation: "Query 'date': Suppose hashes to 1, 3, 5. All are 1 (set by banana, apple, banana). Return 'maybe present' - but we never added 'date'! This is a false positive. Probability depends on bit density and k.", theoryConnection: "False positive = unavoidable but controllable. With m=16, n=3, k=3: FP rate ≈ 2%. To get 0.1% FP, need ~14 bits per element. Google Chrome uses bloom filter for malicious URL checking: <1% FP, saves 99% of disk lookups.", complexity: "Can't distinguish true positive from false positive without external check. Bloom filter is first line of defense." },
  { step: 8, title: "Optimal Configuration", description: "How to choose m (bits) and k (hashes) for target FP rate.", codeLines: [21, 22], bitArray: [true, true, true, true, true, true, true, true, false, true, false, false, false, false, false, false], items: ["apple", "banana", "cherry"], queryItem: null, queryResult: null, hashFunctions: 3, falsePositiveRate: 0.02, explanation: "Optimal k = (m/n) × ln(2). For target FP = p: m = -n × ln(p) / (ln(2)²). Example: 1 million items, 1% FP rate: m ≈ 9.6 million bits (1.2 MB), k ≈ 7. Very space efficient compared to storing actual items!", theoryConnection: "Bloom filters are probabilistic trade-offs. Alternative: Cuckoo filters (support deletion, better FP rate for small sets). XOR filters (immutable, smaller than bloom). Quotient filters (cache-efficient). Choose based on needs.", complexity: "Space-optimal: O(n log(1/p)) bits. Time: O(log(1/p)) hash computations." },
];

export default function BloomFilterVisualizerEnhanced() {
  const { currentStep: stepIndex, totalSteps, isPlaying, playbackSpeed, togglePlay, pause, setStep, nextStep, prevStep, setTotalSteps, setPlaybackSpeed } = useTimeline();
  const { setActiveLines } = useCodeHighlight();
  const [currentStep, setCurrentStep] = useState(0);

  useEffect(() => { setTotalSteps(generateSteps().length); }, [setTotalSteps]);
  useEffect(() => { setCurrentStep(stepIndex); }, [stepIndex]);
  const steps = generateSteps();
  const step = steps[currentStep] || steps[0];
  useEffect(() => { if (step?.codeLines) setActiveLines(step.codeLines); }, [step]);
  useEffect(() => { let interval: NodeJS.Timeout; if (isPlaying && currentStep < steps.length - 1) { interval = setInterval(() => nextStep(), 2500 / playbackSpeed); } else if (currentStep >= steps.length - 1 && isPlaying) pause(); return () => clearInterval(interval); }, [isPlaying, currentStep, steps.length, playbackSpeed, nextStep, pause]);
  const handleReset = useCallback(() => { pause(); setStep(0); }, [pause, setStep]);

  return (
    <div className="w-full h-full flex flex-col bg-[#0d1117] rounded-lg overflow-hidden">
      <div className="flex items-center justify-between p-4 border-b border-[#30363d] bg-[#161b22]">
        <div><h3 className="text-white font-semibold text-lg">Bloom Filters</h3><p className="text-[#8b949e] text-sm">Probabilistic Membership | Space-Efficient | O(1) Query</p></div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1 bg-[#21262d] rounded-lg"><Filter size={14} className="text-[#58a6ff]" /><span className="text-[#8b949e] text-xs">FP Rate:</span><span className="text-[#f0883e] font-bold">{(step.falsePositiveRate * 100).toFixed(1)}%</span></div>
          <div className="w-32 h-2 bg-[#21262d] rounded-full"><div className="h-full bg-[#58a6ff] rounded-full transition-all" style={{ width: `${((currentStep + 1) / steps.length) * 100}%` }} /></div>
        </div>
      </div>
      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 flex flex-col p-6">
          <div className="mb-4"><h4 className="text-[#8b949e] text-sm mb-2">Bit Array (m=16, k=3):</h4><div className="grid grid-cols-8 gap-2">{step.bitArray.map((bit, i) => (<motion.div key={i} initial={{ scale: 0 }} animate={{ scale: 1 }} className={`h-10 rounded-lg flex items-center justify-center font-mono text-sm ${bit ? "bg-[#3fb950] text-white" : "bg-[#21262d] text-[#6e7681]"}`}>{i}</motion.div>))}</div></div>
          <div className="flex-1 bg-[#161b22] rounded-lg p-4">
            <h4 className="text-[#8b949e] text-sm mb-3">Inserted Items:</h4>
            <div className="flex flex-wrap gap-2">{step.items.map((item, i) => (<motion.div key={item} initial={{ scale: 0 }} animate={{ scale: 1 }} className="px-4 py-2 bg-[#3fb950]/20 border border-[#3fb950] rounded-lg text-[#3fb950]">{item}</motion.div>))}</div>
            {step.queryItem && <div className="mt-4"><h4 className="text-[#8b949e] text-sm mb-2">Query: "{step.queryItem}"</h4><div className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg ${step.queryResult === "maybe" ? "bg-[#f0883e]/20 border border-[#f0883e] text-[#f0883e]" : step.queryResult === "no" ? "bg-[#f85149]/20 border border-[#f85149] text-[#f85149]" : "bg-[#21262d] text-[#8b949e]"}`}><HelpCircle size={16} />{step.queryResult === "maybe" ? "Maybe in set (could be FP)" : step.queryResult === "no" ? "Definitely not in set" : "-"}</div></div>}
          </div>
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Items</span><p className="text-white font-bold text-lg">{step.items.length}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Occupancy</span><p className="text-[#f0883e] font-bold text-lg">{Math.round(step.bitArray.filter(Boolean).length / step.bitArray.length * 100)}%</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Hash Funcs</span><p className="text-[#58a6ff] font-bold text-lg">k={step.hashFunctions}</p></div>
          </div>
        </div>
        <div className="w-96 border-l border-[#30363d] bg-[#161b22] flex flex-col">
          <div className="p-5 border-b border-[#30363d]"><span className="text-[#58a6ff] text-xs font-mono uppercase tracking-wider">Step {currentStep + 1}: {step.title}</span><p className="text-[#c9d1d9] mt-3 leading-relaxed">{step.description}</p></div>
          <div className="p-5 border-b border-[#30363d] flex-1 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">What is Happening</h4><p className="text-[#c9d1d9] text-sm leading-relaxed mb-4">{step.explanation}</p><div className="mt-4 p-3 bg-[#238636]/10 border border-[#238636]/30 rounded-lg"><h4 className="text-[#3fb950] text-xs uppercase tracking-wider mb-1">💡 Theory Connection</h4><p className="text-[#c9d1d9] text-sm leading-relaxed">{step.theoryConnection}</p></div><div className="mt-4 p-3 bg-[#58a6ff]/10 border border-[#58a6ff]/30 rounded-lg"><h4 className="text-[#58a6ff] text-xs uppercase tracking-wider mb-1">⏱️ Complexity</h4><p className="text-[#c9d1d9] text-sm font-mono">{step.complexity}</p></div></div>
          <div className="p-4 bg-[#0d1117] max-h-56 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">Code Reference</h4><div className="text-xs font-mono">{codeLines.map((line, i) => (<div key={i} className={`px-2 py-0.5 rounded ${step.codeLines?.includes(i + 1) ? "bg-[#238636]/30 text-[#7ee787] border-l-2 border-[#238636]" : "text-[#8b949e]"}`}><span className="text-[#6e7681] w-6 inline-block select-none">{i + 1}</span>{line || " "}</div>))}</div></div>
        </div>
      </div>
      <div className="p-4 border-t border-[#30363d] bg-[#161b22]">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2"><button onClick={() => { pause(); setStep(0); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipBack size={18} /></button><button onClick={prevStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronLeft size={20} /></button><button onClick={togglePlay} className="px-6 py-2 bg-[#238636] hover:bg-[#2ea043] text-white rounded-lg font-medium flex items-center gap-2">{isPlaying ? <Pause size={18} /> : <Play size={18} />}{isPlaying ? "Pause" : "Play"}</button><button onClick={nextStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronRight size={20} /></button><button onClick={() => { pause(); setStep(steps.length - 1); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipForward size={18} /></button><button onClick={handleReset} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><RotateCcw size={18} /></button></div>
          <div className="flex items-center gap-3"><span className="text-[#8b949e] text-sm">Speed:</span><div className="flex gap-1">{speeds.map(s => <button key={s.value} onClick={() => setPlaybackSpeed(s.value)} className={`px-2 py-1 rounded text-xs font-medium ${playbackSpeed === s.value ? "bg-[#58a6ff] text-white" : "bg-[#21262d] text-[#8b949e]"}`}>{s.label}</button>)}</div></div>
        </div>
      </div>
    </div>
  );
}
