"use client";

import React from "react";
import { motion } from "framer-motion";
import { useState, useEffect, useCallback } from "react";
import { Play, Pause, SkipBack, SkipForward, RotateCcw, ChevronLeft, ChevronRight, Calculator, Table2 } from "lucide-react";
import { useTimeline, useCodeHighlight } from "@/lib/engine/store";

interface Step { step: number; title: string; description: string; codeLines: number[]; n: number; memo: (number | null)[][]; callStack: { fn: string; args: string; result?: number }[]; currentCell?: [number, number]; explanation: string; theoryConnection: string; complexity: string; }

const speeds = [{ label: "0.5x", value: 0.5 }, { label: "1x", value: 1 }, { label: "1.5x", value: 1.5 }, { label: "2x", value: 2 }, { label: "3x", value: 3 }];

const codeLines = ["// Dynamic Programming: Fibonacci with Memoization", "function fib(n, memo = {}) {", "  // Base cases", "  if (n <= 1) return n;", "", "  // Check if already computed", "  if (memo[n] !== undefined) {", "    return memo[n];  // Reuse!", "  }", "", "  // Compute and store", "  memo[n] = fib(n-1, memo) + fib(n-2, memo);", "  return memo[n];", "}", "", "// DP Table Approach (Bottom-Up)", "function fibDP(n) {", "  if (n <= 1) return n;", "", "  const dp = new Array(n + 1);", "  dp[0] = 0;", "  dp[1] = 1;", "", "  for (let i = 2; i <= n; i++) {", "    dp[i] = dp[i-1] + dp[i-2];", "  }", "", "  return dp[n];", "}"];

const generateSteps = (): Step[] => [
  { step: 0, title: "Dynamic Programming Fundamentals", description: "Solve complex problems by breaking them into overlapping subproblems.", codeLines: [1, 2, 3, 4], n: 6, memo: Array(7).fill(null).map(() => Array(2).fill(null)), callStack: [], explanation: "DP is an optimization technique. Two key properties: 1) Optimal Substructure: optimal solution contains optimal subsolutions. 2) Overlapping Subproblems: same subproblems solved multiple times. We'll demonstrate with Fibonacci sequence.", theoryConnection: "DP was pioneered by Richard Bellman in the 1950s. Used extensively in: Bioinformatics (sequence alignment), Economics (optimal control), Operations research, Compiler optimization.", complexity: "Naive recursion: O(2^n). Memoization: O(n). DP table: O(n) time, O(n) space." },
  { step: 1, title: "The Problem: Fibonacci", description: "Fibonacci: F(n) = F(n-1) + F(n-2), with F(0)=0, F(1)=1.", codeLines: [1, 2, 3, 4], n: 6, memo: [[0, 0], [1, 1], [null, null], [null, null], [null, null], [null, null], [null, null]], callStack: [], explanation: "Fibonacci sequence: 0, 1, 1, 2, 3, 5, 8... Computing F(6) requires F(5) and F(4). Naive recursion recomputes same values repeatedly!", theoryConnection: "Fibonacci exhibits both DP properties: Optimal substructure (F(n) built from optimal F(n-1), F(n-2)) and Overlapping subproblems (F(3) needed by both F(5) and F(4)).", complexity: "F(6) = 8. Let's see how to compute it efficiently." },
  { step: 2, title: "Naive Recursion Tree", description: "Without memoization, computing F(5) requires 15 calls! Exponential growth.", codeLines: [2, 3, 4, 11], n: 5, memo: [[0, 0], [1, 1], [null, null], [null, null], [null, null], [null, null]], callStack: [{ fn: "fib", args: "5", result: undefined }], explanation: "Computing fib(5) naively: fib(5) calls fib(4)+fib(3), fib(4) calls fib(3)+fib(2), etc. fib(3) computed twice! fib(2) computed three times! Total calls: 15 for fib(5).", theoryConnection: "Recursion tree has 2^n nodes. Repeated work is the problem. For fib(100), naive approach needs 2^100 ≈ 1.27 × 10^30 calls - impossible!", complexity: "Time: O(2^n). Space: O(n) for call stack." },
  { step: 3, title: "Memoization: Store Results", description: "Before computing, check if result already in memo table.", codeLines: [6, 7, 8, 9], n: 6, memo: [[0, 0], [1, 1], [null, null], [null, null], [null, null], [null, null], [null, null]], callStack: [{ fn: "fib", args: "6", result: undefined }], explanation: "Memoization (top-down DP): Store computed results in table. Before recursive call, check memo. If present, return immediately. No recomputation!", theoryConnection: "Memoization transforms exponential time to linear! Each Fibonacci number computed exactly once. Time becomes O(n), space O(n) for memo + call stack.", complexity: "With memo: O(n) time, O(n) space." },
  { step: 4, title: "Compute F(2)", description: "F(2) = F(1) + F(0) = 1 + 0 = 1. Store in memo.", codeLines: [11, 12, 13], n: 6, memo: [[0, 0], [1, 1], [1, null], [null, null], [null, null], [null, null], [null, null]], callStack: [{ fn: "fib", args: "6" }, { fn: "fib", args: "5" }, { fn: "fib", args: "4" }, { fn: "fib", args: "3" }, { fn: "fib", args: "2" }], explanation: "Computing fib(2): Check memo - not found. Base case? No. Compute fib(1)+fib(0) = 1+0 = 1. Store memo[2]=1. Return 1. This value will be reused!", theoryConnection: "First computation of subproblem. Future calls to fib(2) will hit the memo and return in O(1). The investment in storage pays off exponentially.", complexity: "First time: O(1) to compute. Future: O(1) lookup." },
  { step: 5, title: "Compute F(3)", description: "F(3) = F(2) + F(1) = 1 + 1 = 2. F(2) found in memo!", codeLines: [6, 7, 8, 11], n: 6, memo: [[0, 0], [1, 1], [1, null], [2, null], [null, null], [null, null], [null, null]], callStack: [{ fn: "fib", args: "6" }, { fn: "fib", args: "5" }, { fn: "fib", args: "4" }, { fn: "fib", args: "3", result: 2 }], explanation: "Computing fib(3): fib(2) found in memo instantly (1). fib(1) = 1 (base case). Sum = 2. Store memo[3]=2. Notice we didn't recompute fib(2)!", theoryConnection: "Key insight: memo[2] was computed once, now reused. The savings compound as we go higher. For fib(n), we only compute n values instead of 2^n.", complexity: "O(1) for memo lookup vs O(2^n) to recompute." },
  { step: 6, title: "Bottom-Up DP Table", description: "Iterative approach: fill table from base cases up.", codeLines: [16, 17, 18, 19, 20, 21, 22, 23, 24], n: 6, memo: [[0, 0], [1, 1], [1, 1], [2, 2], [3, 3], [5, 5], [8, 8]], callStack: [], explanation: "Bottom-up DP: Initialize dp[0]=0, dp[1]=1. Iterate i from 2 to n: dp[i] = dp[i-1] + dp[i-2]. No recursion, no call stack overhead. Same O(n) time/space.", theoryConnection: "Bottom-up eliminates recursion overhead and is often faster. More importantly, it enables space optimization - we only need last 2 values, not full table. Can achieve O(1) space!", complexity: "Time: O(n), Space: O(n) or O(1) with optimization." },
  { step: 7, title: "Space Optimization", description: "Only need last 2 values, not full table. O(1) space possible!", codeLines: [16, 17, 18, 19, 20], n: 6, memo: [[0, 0], [1, 1], [1, 1], [2, 2], [3, 3], [5, 5], [8, 8]], callStack: [], explanation: "Observation: to compute dp[i], we only need dp[i-1] and dp[i-2]. No need to store entire table! Just keep 2 variables: a=dp[i-2], b=dp[i-1]. Update: a, b = b, a+b.", theoryConnection: "Space optimization is common in DP. Rolling array technique reduces O(n) space to O(1). Classic examples: Fibonacci, house robber, climbing stairs. Time remains O(n).", complexity: "Optimal: O(n) time, O(1) space!" },
  { step: 8, title: "DP Pattern: 0/1 Knapsack", description: "Another classic DP problem: maximize value with weight constraint.", codeLines: [16, 17, 18, 19, 20], n: 4, memo: [[0, 0, 0, 0, 0, 0], [0, 0, 3, 3, 3, 3], [0, 0, 3, 4, 4, 7], [0, 0, 3, 4, 5, 7], [0, 0, 3, 4, 5, 7]], callStack: [], explanation: "Knapsack: items with weights and values, capacity W. dp[i][w] = max value using first i items with capacity w. Choice: include item i (if fits) or skip it.", theoryConnection: "Knapsack demonstrates DP decision-making. Each state represents a subproblem. Transition considers all choices (include/exclude). 2D table for 2 parameters (items, capacity).", complexity: "Time: O(n × W), Space: O(n × W) or O(W) optimized." },
  { step: 9, title: "When to Use DP", description: "Look for these patterns in problems.", codeLines: [1, 2, 3, 4], n: 6, memo: [[0, 0], [1, 1], [1, 1], [2, 2], [3, 3], [5, 5], [8, 8]], callStack: [], explanation: "Use DP when: 1) Problem asks for optimal value (max/min), 2) Problem asks for count of ways, 3) Problem has sequential decisions, 4) Can identify state parameters, 5) Can write recurrence relation.", theoryConnection: "Common DP problem types: Sequence (LIS, LCS), Knapsack, Grid paths, Interval, Tree DP, Bitmask DP, State machine. Master these patterns!", complexity: "DP is one of the most important interview topics. Practice makes perfect!" },
];

export default function DPVisualizerEnhanced() {
  const { currentStep: stepIndex, totalSteps, isPlaying, playbackSpeed, togglePlay, pause, setStep, nextStep, prevStep, setTotalSteps, setPlaybackSpeed } = useTimeline();
  
  const [currentStep, setCurrentStep] = useState(0);

  useEffect(() => { setTotalSteps(generateSteps().length); }, [setTotalSteps]);
  useEffect(() => { setCurrentStep(stepIndex); }, [stepIndex]);
  const steps = generateSteps();
  const step = steps[currentStep] || steps[0];
  useEffect(() => { if (step?.codeLines) setActiveLines(step.codeLines); }, [step]);
  useEffect(() => { let interval: NodeJS.Timeout; if (isPlaying && currentStep < steps.length - 1) { interval = setInterval(() => nextStep(), 2500 / playbackSpeed); } else if (currentStep >= steps.length - 1 && isPlaying) pause(); return () => clearInterval(interval); }, [isPlaying, currentStep, steps.length, playbackSpeed, nextStep, pause]);
  const handleReset = useCallback(() => { pause(); setStep(0); }, [pause, setStep]);

  return (
    <div className="w-full h-full flex flex-col bg-[#0d1117] rounded-lg overflow-hidden">
      <div className="flex items-center justify-between p-4 border-b border-[#30363d] bg-[#161b22]">
        <div><h3 className="text-white font-semibold text-lg">Dynamic Programming</h3><p className="text-[#8b949e] text-sm">Memoization | Bottom-Up | Overlapping Subproblems</p></div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1 bg-[#21262d] rounded-lg"><Table2 size={14} className="text-[#58a6ff]" /><span className="text-[#8b949e] text-xs">Target:</span><span className="text-[#f0883e] font-bold">F({step.n})</span></div>
          <div className="w-32 h-2 bg-[#21262d] rounded-full"><div className="h-full bg-[#58a6ff] rounded-full transition-all" style={{ width: `${((currentStep + 1) / steps.length) * 100}%` }} /></div>
        </div>
      </div>
      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 flex flex-col p-6">
          <div className="flex-1 flex flex-col justify-center gap-6">
            <div><h4 className="text-[#8b949e] text-sm mb-2">Memoization Table:</h4><div className="flex gap-2">{step.memo.slice(0, step.n + 1).map((row, i) => (<div key={i} className="flex flex-col gap-1"><span className="text-xs text-[#6e7681] text-center">F({i})</span><div className={`w-12 h-12 border-2 rounded-lg flex items-center justify-center font-bold ${row[0] !== null ? "border-[#3fb950] bg-[#3fb950]/20 text-[#3fb950]" : "border-[#30363d] bg-[#21262d] text-[#6e7681]"}`}>{row[0] ?? "?"}</div></div>))}</div></div>
            {step.callStack.length > 0 && <div><h4 className="text-[#8b949e] text-sm mb-2">Call Stack:</h4><div className="flex flex-col gap-1">{step.callStack.map((call, i) => (<div key={i} className="px-3 py-1 bg-[#21262d] rounded-lg border border-[#30363d] text-sm"><span className="text-[#f0883e]">{call.fn}</span><span className="text-[#c9d1d9]">({call.args})</span>{call.result !== undefined && <span className="text-[#3fb950] ml-2">= {call.result}</span>}</div>))}</div></div>}
          </div>
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Computing</span><p className="text-white font-bold text-lg">F({step.n})</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Memoized</span><p className="text-[#3fb950] font-bold text-lg">{step.memo.filter(r => r[0] !== null).length}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Result</span><p className="text-[#58a6ff] font-bold text-lg">{step.memo[step.n]?.[0] ?? "?"}</p></div>
          </div>
        </div>
        <div className="w-96 border-l border-[#30363d] bg-[#161b22] flex flex-col">
          <div className="p-5 border-b border-[#30363d]"><span className="text-[#58a6ff] text-xs font-mono uppercase tracking-wider">Step {currentStep + 1}: {step.title}</span><p className="text-[#c9d1d9] mt-3 leading-relaxed">{step.description}</p></div>
          <div className="p-5 border-b border-[#30363d] flex-1 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">What is Happening</h4><p className="text-[#c9d1d9] text-sm leading-relaxed mb-4">{step.explanation}</p><div className="mt-4 p-3 bg-[#238636]/10 border border-[#238636]/30 rounded-lg"><h4 className="text-[#3fb950] text-xs uppercase tracking-wider mb-1">💡 Theory Connection</h4><p className="text-[#c9d1d9] text-sm leading-relaxed">{step.theoryConnection}</p></div><div className="mt-4 p-3 bg-[#58a6ff]/10 border border-[#58a6ff]/30 rounded-lg"><h4 className="text-[#58a6ff] text-xs uppercase tracking-wider mb-1">⏱️ Complexity</h4><p className="text-[#c9d1d9] text-sm font-mono">{step.complexity}</p></div></div>
          <div className="p-4 bg-[#0d1117] max-h-56 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">Code Reference</h4><div className="text-xs font-mono">{codeLines.map((line, i) => (<div key={i} className={`px-2 py-0.5 rounded ${step.codeLines?.includes(i + 1) ? "bg-[#238636]/30 text-[#7ee787] border-l-2 border-[#238636]" : "text-[#8b949e]"}`}><span className="text-[#6e7681] w-6 inline-block select-none">{i + 1}</span>{line || " "}</div>))}</div></div>
        </div>
      </div>
      <div className="p-4 border-t border-[#30363d] bg-[#161b22]">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2"><button onClick={() => { pause(); setStep(0); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipBack size={18} /></button><button onClick={prevStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronLeft size={20} /></button><button onClick={togglePlay} className="px-6 py-2 bg-[#238636] hover:bg-[#2ea043] text-white rounded-lg font-medium flex items-center gap-2">{isPlaying ? <Pause size={18} /> : <Play size={18} />}{isPlaying ? "Pause" : "Play"}</button><button onClick={nextStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronRight size={20} /></button><button onClick={() => { pause(); setStep(steps.length - 1); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipForward size={18} /></button><button onClick={handleReset} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><RotateCcw size={18} /></button></div>
          <div className="flex items-center gap-3"><span className="text-[#8b949e] text-sm">Speed:</span><div className="flex gap-1">{speeds.map(s => <button key={s.value} onClick={() => setPlaybackSpeed(s.value)} className={`px-2 py-1 rounded text-xs font-medium ${playbackSpeed === s.value ? "bg-[#58a6ff] text-white" : "bg-[#21262d] text-[#8b949e]"}`}>{s.label}</button>)}</div></div>
        </div>
      </div>
    </div>
  );
}
