"use client";

import React from "react";
import { motion } from "framer-motion";
import { useState, useEffect, useCallback } from "react";
import { Play, Pause, SkipBack, SkipForward, RotateCcw, ChevronLeft, ChevronRight, Grid3X3, Search } from "lucide-react";
import { useTimeline, useCodeHighlight } from "@/lib/engine/store";

interface Point { x: number; y: number; label: string; }
interface Node { point: Point; left: number | null; right: number | null; axis: number; }
interface Step { step: number; title: string; description: string; codeLines: number[]; points: Point[]; tree: (Node | null)[]; activeNode: number | null; queryPoint: Point | null; nearest: Point | null; depth: number; explanation: string; theoryConnection: string; complexity: string; }

const speeds = [{ label: "0.5x", value: 0.5 }, { label: "1x", value: 1 }, { label: "1.5x", value: 1.5 }, { label: "2x", value: 2 }, { label: "3x", value: 3 }];

const codeLines = ["// k-d Tree for k-dimensional space", "function buildKDTree(points, depth = 0) {", "  if (points.length === 0) return null;", "", "  const axis = depth % k;  // Cycle through dimensions", "  points.sort((a, b) => a[axis] - b[axis]);", "", "  const mid = Math.floor(points.length / 2);", "  const node = {", "    point: points[mid],", "    left: buildKDTree(points.slice(0, mid), depth + 1),", "    right: buildKDTree(points.slice(mid + 1), depth + 1),", "    axis: axis", "  };", "", "  return node;", "}", "", "// Nearest neighbor search", "function nearest(node, target, depth = 0, best = null) {", "  if (!node) return best;", "", "  const axis = depth % k;", "  let near = target[axis] < node.point[axis] ? node.left : node.right;", "  let far = target[axis] < node.point[axis] ? node.right : node.left;", "", "  best = nearest(near, target, depth + 1, best);", "", "  // Check if we need to explore other side", "  if (distance(target, best) > Math.abs(target[axis] - node.point[axis])) {", "    best = nearest(far, target, depth + 1, best);", "  }", "", "  return closer(best, node.point, target);", "}"];

const points: Point[] = [{ x: 30, y: 40, label: "A" }, { x: 50, y: 20, label: "B" }, { x: 70, y: 60, label: "C" }, { x: 20, y: 70, label: "D" }, { x: 60, y: 30, label: "E" }];

const generateSteps = (): Step[] => [
  { step: 0, title: "k-d Trees", description: "Space-partitioning data structure for organizing points in k-dimensional space.", codeLines: [1, 2, 3], points, tree: [], activeNode: null, queryPoint: null, nearest: null, depth: 0, explanation: "k-d tree = k-dimensional tree. Binary tree where each level splits space along one dimension (x, y, z, ...). Cycles through dimensions: level 0 = x, level 1 = y, level 2 = x, etc. Enables efficient nearest neighbor search, range queries.", theoryConnection: "Invented by Bentley (1975). Generalizes binary search tree to multiple dimensions. Space is recursively partitioned into half-spaces. Each node = splitting hyperplane. Applications: graphics (ray tracing), databases (spatial indexing), machine learning (k-NN), astronomy (star catalogs).", complexity: "Build: O(n log n). Space: O(n). Nearest neighbor: O(log n) average, O(n) worst. Much better than linear scan O(n)." },
  { step: 1, title: "Root Node - X-axis Split", description: "Level 0: Split by x-coordinate. Median becomes root.", codeLines: [5, 6, 7, 8], points, tree: [{ point: { x: 50, y: 20, label: "B" }, left: null, right: null, axis: 0 }], activeNode: 0, queryPoint: null, nearest: null, depth: 0, explanation: "Level 0 (depth 0): axis = 0 % 2 = x. Sort by x: A(20), D(20), B(50), E(60), C(70). Median at index 2: B(50, 20). B becomes root. Points with x < 50 go left, x > 50 go right.", theoryConnection: "Median selection ensures balanced tree (approximately). Balanced k-d tree has height O(log n). Unbalanced can degrade to O(n). Use median-of-medians or randomized selection for guaranteed balance.", complexity: "Finding median: O(n). Build proceeds recursively on left and right halves." },
  { step: 2, title: "Left Subtree - Y-axis Split", description: "Level 1: Left of root, split by y-coordinate.", codeLines: [10, 11], points, tree: [{ point: { x: 50, y: 20, label: "B" }, left: 1, right: 2, axis: 0 }, { point: { x: 30, y: 40, label: "A" }, left: 3, right: null, axis: 1 }], activeNode: 1, queryPoint: null, nearest: null, depth: 1, explanation: "Level 1, left side (A, D): axis = 1 % 2 = y. Sort by y: B already placed. Remaining: sort by y - A(40), D(70). Median: A(30, 40). A becomes left child of B. D (y=70 > 40) goes right of A.", theoryConnection: "Alternating splits create axis-aligned bounding boxes. Left subtree has x < 50, right has x > 50. Within left, lower part has y < 40 (none), upper has y > 40 (D). Space partitioning enables pruning in search.", complexity: "Recursive build. Each level processes half the points. Total: O(n log n)." },
  { step: 3, title: "Right Subtree - Y-axis Split", description: "Level 1: Right of root, split by y-coordinate.", codeLines: [12], points, tree: [{ point: { x: 50, y: 20, label: "B" }, left: 1, right: 2, axis: 0 }, { point: { x: 30, y: 40, label: "A" }, left: 3, right: null, axis: 1 }, { point: { x: 70, y: 60, label: "C" }, left: 4, right: null, axis: 1 }], activeNode: 2, queryPoint: null, nearest: null, depth: 1, explanation: "Level 1, right side (C, E): axis = y. Sort by y: E(30), C(60). Median: C(70, 60). C becomes right child of B. E (y=30 < 60) goes left of C. Tree is now complete with 5 nodes.", theoryConnection: "Tree is balanced (height ≈ log n). Each level halves the point set. Leaf nodes contain single points. Internal nodes store splitting points. Empty children = null.", complexity: "Balanced k-d tree height: ⌈log₂(n)⌉. Space: n nodes, each with point + 2 pointers + axis flag." },
  { step: 4, title: "Nearest Neighbor Query", description: "Find point closest to query Q(45, 35).", codeLines: [19, 20, 21], points, tree: [{ point: { x: 50, y: 20, label: "B" }, left: 1, right: 2, axis: 0 }, { point: { x: 30, y: 40, label: "A" }, left: 3, right: null, axis: 1 }, { point: { x: 70, y: 60, label: "C" }, left: 4, right: null, axis: 1 }, { point: { x: 20, y: 70, label: "D" }, left: null, right: null, axis: 0 }, { point: { x: 60, y: 30, label: "E" }, left: null, right: null, axis: 0 }], activeNode: 0, queryPoint: { x: 45, y: 35, label: "Q" }, nearest: null, depth: 0, explanation: "Query: find nearest to Q(45, 35). Start at root B(50, 20). Distance² = (45-50)² + (35-20)² = 25 + 225 = 250. Current best = B. Q.x=45 < B.x=50, go left.", theoryConnection: "Search follows tree structure like BST but with alternating comparisons. At each node, compare query's relevant coordinate to node's point. Recurse into appropriate subtree first.", complexity: "First descent: O(log n). May need to check other subtrees." },
  { step: 5, title: "Pruning Search", description: "Check if other side of split could contain closer point.", codeLines: [24, 25, 26, 27, 28], points, tree: [{ point: { x: 50, y: 20, label: "B" }, left: 1, right: 2, axis: 0 }, { point: { x: 30, y: 40, label: "A" }, left: 3, right: null, axis: 1 }, { point: { x: 70, y: 60, label: "C" }, left: 4, right: null, axis: 1 }, { point: { x: 20, y: 70, label: "D" }, left: null, right: null, axis: 0 }, { point: { x: 60, y: 30, label: "E" }, left: null, right: null, axis: 0 }], activeNode: 1, queryPoint: { x: 45, y: 35, label: "Q" }, nearest: { x: 50, y: 20, label: "B" }, depth: 1, explanation: "At A(30, 40): dist² = (45-30)² + (35-40)² = 225 + 25 = 250. Equal to B! Q.y=35 < A.y=40, go left to D. At D(20, 70): dist² = (45-20)² + (35-70)² = 625 + 1225 = 1850 > 250. No better. Back up to A. Check if right subtree of A could have closer point.", theoryConnection: "Key optimization: if |query[axis] - node.point[axis]| > best_distance, points on other side cannot be closer (hyperplane separation). Prune entire subtree! This makes k-d tree efficient.", complexity: "Pruning can eliminate large portions of tree. Average case: O(log n). Worst case (query near all points): O(n)." },
  { step: 6, title: "Complete Search", description: "Verify all potentially better points are checked.", codeLines: [24, 25, 26, 27, 28], points, tree: [{ point: { x: 50, y: 20, label: "B" }, left: 1, right: 2, axis: 0 }, { point: { x: 30, y: 40, label: "A" }, left: 3, right: null, axis: 1 }, { point: { x: 70, y: 60, label: "C" }, left: 4, right: null, axis: 1 }, { point: { x: 20, y: 70, label: "D" }, left: null, right: null, axis: 0 }, { point: { x: 60, y: 30, label: "E" }, left: null, right: null, axis: 0 }], activeNode: 2, queryPoint: { x: 45, y: 35, label: "Q" }, nearest: { x: 30, y: 40, label: "A" }, depth: 2, explanation: "At A: |Q.y - A.y| = |35-40| = 5. √250 ≈ 15.8 > 5, so we must check other side. But A has no right child. Back to root B: |Q.x - B.x| = |45-50| = 5. √250 ≈ 15.8 > 5, check right subtree. At C(70, 60): dist² = (45-70)² + (35-60)² = 625 + 625 = 1250 > 250. Check left of C: E(60, 30): dist² = (45-60)² + (35-30)² = 225 + 25 = 250. Equal! A is closest (or tie).", theoryConnection: "Both A and B (and E) are equally close in this example. Real implementation would update best whenever strictly closer found. Multiple nearest points possible.", complexity: "Final nearest neighbor found. Compared B, A, D, C, E. Pruned nothing in this small example. With more points, pruning saves significant work." },
];

export default function KDTreeVisualizerEnhanced() {
  const { currentStep: stepIndex, totalSteps, isPlaying, playbackSpeed, togglePlay, pause, setStep, nextStep, prevStep, setTotalSteps, setPlaybackSpeed } = useTimeline();
  const { setActiveLines } = useCodeHighlight();
  const [currentStep, setCurrentStep] = useState(0);

  useEffect(() => { setTotalSteps(generateSteps().length); }, [setTotalSteps]);
  useEffect(() => { setCurrentStep(stepIndex); }, [stepIndex]);
  const steps = generateSteps();
  const step = steps[currentStep] || steps[0];
  useEffect(() => { if (step?.codeLines) setActiveLines(step.codeLines); }, [step, setActiveLines]);
  useEffect(() => { let interval: NodeJS.Timeout; if (isPlaying && currentStep < steps.length - 1) { interval = setInterval(() => nextStep(), 2500 / playbackSpeed); } else if (currentStep >= steps.length - 1 && isPlaying) pause(); return () => clearInterval(interval); }, [isPlaying, currentStep, steps.length, playbackSpeed, nextStep, pause]);
  const handleReset = useCallback(() => { pause(); setStep(0); }, [pause, setStep]);

  return (
    <div className="w-full h-full flex flex-col bg-[#0d1117] rounded-lg overflow-hidden">
      <div className="flex items-center justify-between p-4 border-b border-[#30363d] bg-[#161b22]">
        <div><h3 className="text-white font-semibold text-lg">k-d Trees</h3><p className="text-[#8b949e] text-sm">k-Dimensional Space Partitioning | Nearest Neighbor</p></div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1 bg-[#21262d] rounded-lg"><Grid3X3 size={14} className="text-[#58a6ff]" /><span className="text-[#8b949e] text-xs">k=</span><span className="text-[#f0883e] font-bold">2</span></div>
          <div className="w-32 h-2 bg-[#21262d] rounded-full"><div className="h-full bg-[#58a6ff] rounded-full transition-all" style={{ width: `${((currentStep + 1) / steps.length) * 100}%` }} /></div>
        </div>
      </div>
      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 flex flex-col p-6">
          <div className="flex-1 relative bg-[#161b22] rounded-lg border border-[#30363d]">
            <svg viewBox="0 0 100 100" className="w-full h-full">
              {step.depth >= 0 && <line x1="50" y1="0" x2="50" y2="100" stroke="#58a6ff" strokeWidth="0.5" strokeDasharray="2" />}
              {step.depth >= 1 && <line x1="0" y1="40" x2="50" y2="40" stroke="#3fb950" strokeWidth="0.5" strokeDasharray="2" />}
              {step.depth >= 1 && <line x1="50" y1="60" x2="100" y2="60" stroke="#3fb950" strokeWidth="0.5" strokeDasharray="2" />}
              {step.points.map((p, i) => (<motion.circle key={p.label} cx={p.x} cy={100 - p.y} r="3" fill={step.nearest?.label === p.label ? "#3fb950" : step.activeNode !== null && step.tree[step.activeNode]?.point.label === p.label ? "#f0883e" : "#58a6ff"} stroke="white" strokeWidth="0.5" initial={{ scale: 0 }} animate={{ scale: 1 }} />))}
              {step.queryPoint && <motion.circle cx={step.queryPoint.x} cy={100 - step.queryPoint.y} r="4" fill="none" stroke="#f0883e" strokeWidth="1" initial={{ scale: 0 }} animate={{ scale: 1 }} />}
              {step.nearest && step.queryPoint && <line x1={step.queryPoint.x} y1={100 - step.queryPoint.y} x2={step.nearest.x} y2={100 - step.nearest.y} stroke="#f0883e" strokeWidth="0.5" strokeDasharray="2" />}
            </svg>
          </div>
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Points</span><p className="text-white font-bold text-lg">{step.points.length}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Query</span><p className="text-[#f0883e] font-bold text-lg">{step.queryPoint ? "Q" : "-"}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Nearest</span><p className="text-[#3fb950] font-bold text-lg">{step.nearest?.label || "-"}</p></div>
          </div>
        </div>
        <div className="w-96 border-l border-[#30363d] bg-[#161b22] flex flex-col">
          <div className="p-5 border-b border-[#30363d]"><span className="text-[#58a6ff] text-xs font-mono uppercase tracking-wider">Step {currentStep + 1}: {step.title}</span><p className="text-[#c9d1d9] mt-3 leading-relaxed">{step.description}</p></div>
          <div className="p-5 border-b border-[#30363d] flex-1 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">What is Happening</h4><p className="text-[#c9d1d9] text-sm leading-relaxed mb-4">{step.explanation}</p><div className="mt-4 p-3 bg-[#238636]/10 border border-[#238636]/30 rounded-lg"><h4 className="text-[#3fb950] text-xs uppercase tracking-wider mb-1">💡 Theory Connection</h4><p className="text-[#c9d1d9] text-sm leading-relaxed">{step.theoryConnection}</p></div><div className="mt-4 p-3 bg-[#58a6ff]/10 border border-[#58a6ff]/30 rounded-lg"><h4 className="text-[#58a6ff] text-xs uppercase tracking-wider mb-1">⏱️ Complexity</h4><p className="text-[#c9d1d9] text-sm font-mono">{step.complexity}</p></div></div>
          <div className="p-4 bg-[#0d1117] max-h-56 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">Code Reference</h4><div className="text-xs font-mono">{codeLines.map((line, i) => (<div key={i} className={`px-2 py-0.5 rounded ${step.codeLines?.includes(i + 1) ? "bg-[#238636]/30 text-[#7ee787] border-l-2 border-[#238636]" : "text-[#8b949e]"}`}><span className="text-[#6e7681] w-6 inline-block select-none">{i + 1}</span>{line || " "}</div>))}</div></div>
        </div>
      </div>
      <div className="p-4 border-t border-[#30363d] bg-[#161b22]">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2"><button onClick={() => { pause(); setStep(0); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipBack size={18} /></button><button onClick={prevStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronLeft size={20} /></button><button onClick={togglePlay} className="px-6 py-2 bg-[#238636] hover:bg-[#2ea043] text-white rounded-lg font-medium flex items-center gap-2">{isPlaying ? <Pause size={18} /> : <Play size={18} />}{isPlaying ? "Pause" : "Play"}</button><button onClick={nextStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronRight size={20} /></button><button onClick={() => { pause(); setStep(steps.length - 1); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipForward size={18} /></button><button onClick={handleReset} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><RotateCcw size={18} /></button></div>
          <div className="flex items-center gap-3"><span className="text-[#8b949e] text-sm">Speed:</span><div className="flex gap-1">{speeds.map(s => <button key={s.value} onClick={() => setPlaybackSpeed(s.value)} className={`px-2 py-1 rounded text-xs font-medium ${playbackSpeed === s.value ? "bg-[#58a6ff] text-white" : "bg-[#21262d] text-[#8b949e]"}`}>{s.label}</button>)}</div></div>
        </div>
      </div>
    </div>
  );
}
