"use client";

import React from "react";
import { motion } from "framer-motion";
import { useState, useEffect, useCallback } from "react";
import { Play, Pause, SkipBack, SkipForward, RotateCcw, ChevronLeft, ChevronRight, ArrowRightLeft, Droplets } from "lucide-react";
import { useTimeline, useCodeHighlight } from "@/lib/engine/store";

interface Edge { from: string; to: string; capacity: number; flow: number; residual: number; }
interface Step { step: number; title: string; description: string; codeLines: number[]; nodes: string[]; edges: Edge[]; source: string; sink: string; maxFlow: number; augmentingPath: string[] | null; explanation: string; theoryConnection: string; complexity: string; }

const speeds = [{ label: "0.5x", value: 0.5 }, { label: "1x", value: 1 }, { label: "1.5x", value: 1.5 }, { label: "2x", value: 2 }, { label: "3x", value: 3 }];

const codeLines = ["// Ford-Fulkerson: Max Flow", "function maxFlow(graph, source, sink) {", "  let flow = 0;", "  let parent = {};", "", "  while (bfs(source, sink, parent)) {", "    // Find minimum residual capacity", "    let pathFlow = Infinity;", "    let s = sink;", "    while (s !== source) {", "      pathFlow = Math.min(pathFlow, residual[parent[s]][s]);", "      s = parent[s];", "    }", "", "    // Update residual capacities", "    let v = sink;", "    while (v !== source) {", "      let u = parent[v];", "      residual[u][v] -= pathFlow;", "      residual[v][u] += pathFlow;", "      v = u;", "    }", "", "    flow += pathFlow;", "  }", "", "  return flow;", "}"];

const generateSteps = (): Step[] => [
  { step: 0, title: "Network Flow", description: "Maximize flow from source to sink in a capacitated network. Ford-Fulkerson method.", codeLines: [1, 2, 3], nodes: ["S", "A", "B", "C", "D", "T"], edges: [{ from: "S", to: "A", capacity: 10, flow: 0, residual: 10 }, { from: "S", to: "C", capacity: 10, flow: 0, residual: 10 }, { from: "A", to: "B", capacity: 4, flow: 0, residual: 4 }, { from: "A", to: "D", capacity: 8, flow: 0, residual: 8 }, { from: "C", to: "B", capacity: 9, flow: 0, residual: 9 }, { from: "C", to: "D", capacity: 6, flow: 0, residual: 6 }, { from: "B", to: "T", capacity: 10, flow: 0, residual: 10 }, { from: "D", to: "T", capacity: 10, flow: 0, residual: 10 }], source: "S", sink: "T", maxFlow: 0, augmentingPath: null, explanation: "Network flow problem: direct flow through network from source (S) to sink (T), respecting edge capacities. Goal: maximize total flow. Applications: transportation, computer networks, matching problems, project selection.", theoryConnection: "Max-flow min-cut theorem: maximum flow equals minimum cut capacity. Cut = partition separating S from T. Min-cut is bottleneck. Ford-Fulkerson (1956): repeatedly find augmenting paths in residual graph. Edmonds-Karp: BFS for shortest augmenting path - O(VE²).", complexity: "Ford-Fulkerson: O(E × max_flow) = pseudo-polynomial. Edmonds-Karp: O(V × E²). Dinic's: O(V² × E) or O(E × √V) for unit capacities." },
  { step: 1, title: "Residual Graph", description: "Track remaining capacity and reverse flow capability.", codeLines: [17, 18, 19], nodes: ["S", "A", "B", "C", "D", "T"], edges: [{ from: "S", to: "A", capacity: 10, flow: 0, residual: 10 }, { from: "S", to: "C", capacity: 10, flow: 0, residual: 10 }, { from: "A", to: "B", capacity: 4, flow: 0, residual: 4 }, { from: "A", to: "D", capacity: 8, flow: 0, residual: 8 }, { from: "C", to: "B", capacity: 9, flow: 0, residual: 9 }, { from: "C", to: "D", capacity: 6, flow: 0, residual: 6 }, { from: "B", to: "T", capacity: 10, flow: 0, residual: 10 }, { from: "D", to: "T", capacity: 10, flow: 0, residual: 10 }], source: "S", sink: "T", maxFlow: 0, augmentingPath: null, explanation: "Residual capacity = capacity - flow. Initially all residual = capacity. Residual graph also includes reverse edges with capacity = flow (to allow undoing flow). This enables flow to be rerouted for better overall solution.", theoryConnection: "Residual graph G_f: for each edge (u,v) with capacity c and flow f, add edge with residual capacity c-f. If f > 0, add reverse edge (v,u) with capacity f. Augmenting path = path from S to T in residual graph with positive residual capacity.", complexity: "Residual graph doubles edges (forward + backward). Space: O(E)." },
  { step: 2, title: "Augmenting Path 1: S→A→D→T", description: "BFS finds path. Bottleneck = 8. Augment flow by 8.", codeLines: [6, 7, 8, 9, 10, 11, 12], nodes: ["S", "A", "B", "C", "D", "T"], edges: [{ from: "S", to: "A", capacity: 10, flow: 8, residual: 2 }, { from: "S", to: "C", capacity: 10, flow: 0, residual: 10 }, { from: "A", to: "B", capacity: 4, flow: 0, residual: 4 }, { from: "A", to: "D", capacity: 8, flow: 8, residual: 0 }, { from: "C", to: "B", capacity: 9, flow: 0, residual: 9 }, { from: "C", to: "D", capacity: 6, flow: 0, residual: 6 }, { from: "B", to: "T", capacity: 10, flow: 0, residual: 10 }, { from: "D", to: "T", capacity: 10, flow: 8, residual: 2 }], source: "S", sink: "T", maxFlow: 8, augmentingPath: ["S", "A", "D", "T"], explanation: "Path S→A→D→T has residuals 10, 8, 10. Bottleneck = min = 8. Send 8 units. Update: S→A: flow=8, residual=2. A→D: flow=8, residual=0 (saturated!). D→T: flow=8, residual=2. Total flow = 8.", theoryConnection: "Augmenting path found by BFS (Edmonds-Karp) or DFS. Bottleneck is limiting edge. Saturated edge (A→D) can't carry more flow. May need to find alternative routes or undo some flow via backward edges.", complexity: "Path finding: O(E) with BFS. Augmentation: O(V) to update path." },
  { step: 3, title: "Augmenting Path 2: S→C→B→T", description: "Find alternative path avoiding saturated edge. Bottleneck = 9.", codeLines: [6, 7, 8, 9, 10, 11, 12, 15, 16, 17, 18, 19, 20, 21], nodes: ["S", "A", "B", "C", "D", "T"], edges: [{ from: "S", to: "A", capacity: 10, flow: 8, residual: 2 }, { from: "S", to: "C", capacity: 10, flow: 9, residual: 1 }, { from: "A", to: "B", capacity: 4, flow: 0, residual: 4 }, { from: "A", to: "D", capacity: 8, flow: 8, residual: 0 }, { from: "C", to: "B", capacity: 9, flow: 9, residual: 0 }, { from: "C", to: "D", capacity: 6, flow: 0, residual: 6 }, { from: "B", to: "T", capacity: 10, flow: 9, residual: 1 }, { from: "D", to: "T", capacity: 10, flow: 8, residual: 2 }], source: "S", sink: "T", maxFlow: 17, augmentingPath: ["S", "C", "B", "T"], explanation: "Path S→C→B→T has residuals 10, 9, 10. Bottleneck = 9. Send 9 units. S→C: flow=9, res=1. C→B: saturated (flow=9, res=0). B→T: flow=9, res=1. Total flow = 8 + 9 = 17.", theoryConnection: "Multiple augmenting paths combine to achieve max flow. Each path may share edges but uses residual capacity. Edmonds-Karp guarantees at most O(V×E) augmentations. Each augmentation increases flow by at least 1 (integer capacities).", complexity: "This path took 9 units. C→B now saturated too." },
  { step: 4, title: "Augmenting Path 3: S→A→B→T", description: "Use remaining capacity on S→A and A→B. Bottleneck = 2.", codeLines: [6, 15, 20], nodes: ["S", "A", "B", "C", "D", "T"], edges: [{ from: "S", to: "A", capacity: 10, flow: 10, residual: 0 }, { from: "S", to: "C", capacity: 10, flow: 9, residual: 1 }, { from: "A", to: "B", capacity: 4, flow: 2, residual: 2 }, { from: "A", to: "D", capacity: 8, flow: 8, residual: 0 }, { from: "C", to: "B", capacity: 9, flow: 9, residual: 0 }, { from: "C", to: "D", capacity: 6, flow: 0, residual: 6 }, { from: "B", to: "T", capacity: 10, flow: 10, residual: 0 }, { from: "D", to: "T", capacity: 10, flow: 8, residual: 2 }], source: "S", sink: "T", maxFlow: 19, augmentingPath: ["S", "A", "B", "T"], explanation: "Path S→A→B→T: residuals 2, 4, 1. Bottleneck = 2. Send 2 units. S→A: now saturated (flow=10). A→B: flow=2, res=2. B→T: saturated (flow=10). Total flow = 17 + 2 = 19.", theoryConnection: "Now multiple edges saturated: S→A, A→D, C→B, B→T. Network is nearly at capacity. Need to find remaining paths. S→C still has 1 unit. D→T still has 2 units. Can we route through C→D?", complexity: "S→A saturated. S→C has 1 unit left. D→T has 2 units left." },
  { step: 5, title: "Augmenting Path 4: S→C→D→T", description: "Final path using C→D edge. Bottleneck = 1.", codeLines: [6, 15, 20], nodes: ["S", "A", "B", "C", "D", "T"], edges: [{ from: "S", to: "A", capacity: 10, flow: 10, residual: 0 }, { from: "S", to: "C", capacity: 10, flow: 10, residual: 0 }, { from: "A", to: "B", capacity: 4, flow: 2, residual: 2 }, { from: "A", to: "D", capacity: 8, flow: 8, residual: 0 }, { from: "C", to: "B", capacity: 9, flow: 9, residual: 0 }, { from: "C", to: "D", capacity: 6, flow: 1, residual: 5 }, { from: "B", to: "T", capacity: 10, flow: 10, residual: 0 }, { from: "D", to: "T", capacity: 10, flow: 9, residual: 1 }], source: "S", sink: "T", maxFlow: 20, augmentingPath: ["S", "C", "D", "T"], explanation: "Path S→C→D→T: residuals 1, 6, 2. Bottleneck = 1. Send 1 unit. S→C: now saturated (flow=10). C→D: flow=1. D→T: flow=9, res=1. Total flow = 19 + 1 = 20. No more augmenting paths from S (both S→A and S→C saturated).", theoryConnection: "No augmenting path exists in residual graph. Algorithm terminates. Max flow = 20. Min cut: partition {S} from {A,B,C,D,T}. Cut edges: S→A (cap 10), S→C (cap 10). Cut capacity = 20 = max flow. Confirms max-flow min-cut theorem!", complexity: "Total augmentations: 4. Final max flow: 20. Algorithm complete." },
  { step: 6, title: "Max Flow Achieved", description: "No more augmenting paths. Maximum flow = 20.", codeLines: [24], nodes: ["S", "A", "B", "C", "D", "T"], edges: [{ from: "S", to: "A", capacity: 10, flow: 10, residual: 0 }, { from: "S", to: "C", capacity: 10, flow: 10, residual: 0 }, { from: "A", to: "B", capacity: 4, flow: 2, residual: 2 }, { from: "A", to: "D", capacity: 8, flow: 8, residual: 0 }, { from: "C", to: "B", capacity: 9, flow: 9, residual: 0 }, { from: "C", to: "D", capacity: 6, flow: 1, residual: 5 }, { from: "B", to: "T", capacity: 10, flow: 10, residual: 0 }, { from: "D", to: "T", capacity: 10, flow: 9, residual: 1 }], source: "S", sink: "T", maxFlow: 20, augmentingPath: null, explanation: "Maximum flow = 20. Flow conservation at each node (in = out, except S and T). Saturated edges form min-cut. Algorithm used 4 augmenting paths. Solution is optimal per max-flow min-cut theorem.", theoryConnection: "Applications: Bipartite matching (model as flow), circulation problems, minimum cost flow, multi-commodity flow. Advanced algorithms: Push-relabel (Goldberg-Tarjan, O(V³)), Dinic's with dynamic trees, capacity scaling.", complexity: "Final result: O(VE²) for Edmonds-Karp. Faster algorithms exist for special cases and dense graphs." },
];

export default function NetworkFlowVisualizerEnhanced() {
  const { currentStep: stepIndex, totalSteps, isPlaying, playbackSpeed, togglePlay, pause, setStep, nextStep, prevStep, setTotalSteps, setPlaybackSpeed } = useTimeline();
  const { setActiveLines } = useCodeHighlight();
  const [currentStep, setCurrentStep] = useState(0);

  useEffect(() => { setTotalSteps(generateSteps().length); }, [setTotalSteps]);
  useEffect(() => { setCurrentStep(stepIndex); }, [stepIndex]);
  const steps = generateSteps();
  const step = steps[currentStep] || steps[0];
  useEffect(() => { if (step?.codeLines) setActiveLines(step.codeLines); }, [step]);
  useEffect(() => { let interval: NodeJS.Timeout; if (isPlaying && currentStep < steps.length - 1) { interval = setInterval(() => nextStep(), 2500 / playbackSpeed); } else if (currentStep >= steps.length - 1 && isPlaying) pause(); return () => clearInterval(interval); }, [isPlaying, currentStep, steps.length, playbackSpeed, nextStep, pause]);
  const handleReset = useCallback(() => { pause(); setStep(0); }, [pause, setStep]);

  const nodePos: Record<string, { x: number; y: number }> = { S: { x: 10, y: 50 }, A: { x: 35, y: 25 }, B: { x: 35, y: 75 }, C: { x: 35, y: 50 }, D: { x: 60, y: 50 }, T: { x: 85, y: 50 } };

  return (
    <div className="w-full h-full flex flex-col bg-[#0d1117] rounded-lg overflow-hidden">
      <div className="flex items-center justify-between p-4 border-b border-[#30363d] bg-[#161b22]">
        <div><h3 className="text-white font-semibold text-lg">Network Flow</h3><p className="text-[#8b949e] text-sm">Ford-Fulkerson | Max Flow | Augmenting Paths</p></div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1 bg-[#21262d] rounded-lg"><Droplets size={14} className="text-[#58a6ff]" /><span className="text-[#8b949e] text-xs">Max Flow:</span><span className="text-[#3fb950] font-bold">{step.maxFlow}</span></div>
          <div className="w-32 h-2 bg-[#21262d] rounded-full"><div className="h-full bg-[#58a6ff] rounded-full transition-all" style={{ width: `${((currentStep + 1) / steps.length) * 100}%` }} /></div>
        </div>
      </div>
      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 flex flex-col p-6">
          <div className="flex-1 relative bg-[#161b22] rounded-lg border border-[#30363d]">
            <svg viewBox="0 0 100 100" className="w-full h-full">
              {step.edges.map((e, i) => {
                const from = nodePos[e.from]; const to = nodePos[e.to];
                const isInPath = step.augmentingPath?.includes(e.from) && step.augmentingPath?.includes(e.to) && Math.abs(step.augmentingPath.indexOf(e.from) - step.augmentingPath.indexOf(e.to)) === 1;
                return (<g key={i}><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} stroke={isInPath ? "#f0883e" : e.residual === 0 ? "#f85149" : "#58a6ff"} strokeWidth={isInPath ? 1.5 : 0.8} markerEnd="url(#arrow)" /><text x={(from.x + to.x) / 2} y={(from.y + to.y) / 2 - 2} fill="#8b949e" fontSize="4" textAnchor="middle">{e.flow}/{e.capacity}</text></g>);
              })}
              {Object.entries(nodePos).map(([label, pos]) => (<motion.g key={label} initial={{ scale: 0 }} animate={{ scale: 1 }}><circle cx={pos.x} cy={pos.y} r="4" fill={label === step.source ? "#3fb950" : label === step.sink ? "#f85149" : "#58a6ff"} stroke="white" strokeWidth="0.5" /><text x={pos.x} y={pos.y + 8} fill="white" fontSize="4" textAnchor="middle">{label}</text></motion.g>))}
            </svg>
          </div>
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Nodes</span><p className="text-white font-bold text-lg">{step.nodes.length}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Edges</span><p className="text-white font-bold text-lg">{step.edges.length}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Saturated</span><p className="text-[#f0883e] font-bold text-lg">{step.edges.filter(e => e.residual === 0).length}</p></div>
          </div>
        </div>
        <div className="w-96 border-l border-[#30363d] bg-[#161b22] flex flex-col">
          <div className="p-5 border-b border-[#30363d]"><span className="text-[#58a6ff] text-xs font-mono uppercase tracking-wider">Step {currentStep + 1}: {step.title}</span><p className="text-[#c9d1d9] mt-3 leading-relaxed">{step.description}</p></div>
          <div className="p-5 border-b border-[#30363d] flex-1 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">What is Happening</h4><p className="text-[#c9d1d9] text-sm leading-relaxed mb-4">{step.explanation}</p><div className="mt-4 p-3 bg-[#238636]/10 border border-[#238636]/30 rounded-lg"><h4 className="text-[#3fb950] text-xs uppercase tracking-wider mb-1">💡 Theory Connection</h4><p className="text-[#c9d1d9] text-sm leading-relaxed">{step.theoryConnection}</p></div><div className="mt-4 p-3 bg-[#58a6ff]/10 border border-[#58a6ff]/30 rounded-lg"><h4 className="text-[#58a6ff] text-xs uppercase tracking-wider mb-1">⏱️ Complexity</h4><p className="text-[#c9d1d9] text-sm font-mono">{step.complexity}</p></div></div>
          <div className="p-4 bg-[#0d1117] max-h-56 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">Code Reference</h4><div className="text-xs font-mono">{codeLines.map((line, i) => (<div key={i} className={`px-2 py-0.5 rounded ${step.codeLines?.includes(i + 1) ? "bg-[#238636]/30 text-[#7ee787] border-l-2 border-[#238636]" : "text-[#8b949e]"}`}><span className="text-[#6e7681] w-6 inline-block select-none">{i + 1}</span>{line || " "}</div>))}</div></div>
        </div>
      </div>
      <div className="p-4 border-t border-[#30363d] bg-[#161b22]">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2"><button onClick={() => { pause(); setStep(0); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipBack size={18} /></button><button onClick={prevStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronLeft size={20} /></button><button onClick={togglePlay} className="px-6 py-2 bg-[#238636] hover:bg-[#2ea043] text-white rounded-lg font-medium flex items-center gap-2">{isPlaying ? <Pause size={18} /> : <Play size={18} />}{isPlaying ? "Pause" : "Play"}</button><button onClick={nextStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronRight size={20} /></button><button onClick={() => { pause(); setStep(steps.length - 1); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipForward size={18} /></button><button onClick={handleReset} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><RotateCcw size={18} /></button></div>
          <div className="flex items-center gap-3"><span className="text-[#8b949e] text-sm">Speed:</span><div className="flex gap-1">{speeds.map(s => <button key={s.value} onClick={() => setPlaybackSpeed(s.value)} className={`px-2 py-1 rounded text-xs font-medium ${playbackSpeed === s.value ? "bg-[#58a6ff] text-white" : "bg-[#21262d] text-[#8b949e]"}`}>{s.label}</button>)}</div></div>
        </div>
      </div>
    </div>
  );
}
