"use client";

import React from "react";
import { motion } from "framer-motion";
import { useState, useEffect, useCallback } from "react";
import { Play, Pause, SkipBack, SkipForward, RotateCcw, ChevronLeft, ChevronRight, FileText, Search } from "lucide-react";
import { useTimeline, useCodeHighlight } from "@/lib/engine/store";

interface Node { id: string; label: string; children: string[]; parent: string | null; start: number; end: number; }
interface Step { step: number; title: string; description: string; codeLines: number[]; text: string; nodes: Node[]; activeNode: string | null; pattern: string; matches: number[]; explanation: string; theoryConnection: string; complexity: string; }

const speeds = [{ label: "0.5x", value: 0.5 }, { label: "1x", value: 1 }, { label: "1.5x", value: 1.5 }, { label: "2x", value: 2 }, { label: "3x", value: 3 }];

const codeLines = ["// Suffix Tree - Compact representation of all suffixes", "function buildSuffixTree(text) {", "  const root = { children: {} };", "  // Add all suffixes to tree", "  for (let i = 0; i < text.length; i++) {", "    addSuffix(root, text.substring(i), i);", "  }", "  return root;", "}", "", "// Pattern search in O(m) time", "function search(root, pattern) {", "  let node = root;", "  for (const char of pattern) {", "    if (!node.children[char]) return [];", "    node = node.children[char];", "  }", "  // All leaves under this node are matches", "  return getAllLeafIndices(node);", "}"];

const generateSteps = (): Step[] => [
  { step: 0, title: "Suffix Trees", description: "Compact trie containing all suffixes of a text. Enables fast pattern matching.", codeLines: [1, 2, 3], text: "banana", nodes: [{ id: "root", label: "root", children: [], parent: null, start: 0, end: 0 }], activeNode: "root", pattern: "ana", matches: [], explanation: "Suffix tree stores all suffixes of text in compressed form. Text 'banana' has suffixes: banana, anana, nana, ana, na, a. Built in O(n) or O(n²) time. Pattern search: O(m) where m = pattern length!", theoryConnection: "Invented by Weiner (1973), improved by McCreight (1976) and Ukkonen (1995). Enables: pattern matching, longest repeated substring, longest common substring, palindrome detection. Used in bioinformatics (DNA sequencing).", complexity: "Construction: O(n) with Ukkonen's algorithm. Space: O(n). Search: O(m) - independent of text size!" },
  { step: 1, title: "Add Suffix: banana", description: "Insert first suffix 'banana' starting at index 0.", codeLines: [4, 5, 6], text: "banana", nodes: [{ id: "root", label: "root", children: ["banana"], parent: null, start: 0, end: 0 }, { id: "banana", label: "banana", children: [], parent: "root", start: 0, end: 5 }], activeNode: "banana", pattern: "ana", matches: [], explanation: "First suffix: 'banana' (indices 0-5). Create path from root with label 'banana'. Leaf represents full suffix starting at position 0. Each leaf stores the starting index of its suffix.", theoryConnection: "Naive construction: insert each suffix into trie. Takes O(n²) time and space. Not practical for large texts. Need edge compression (path compression) to reduce space.", complexity: "First suffix: O(n) to insert. Total naive: O(n²)." },
  { step: 2, title: "Add Suffix: anana", description: "Insert second suffix 'anana' starting at index 1.", codeLines: [4, 5, 6], text: "banana", nodes: [{ id: "root", label: "root", children: ["banana", "anana"], parent: null, start: 0, end: 0 }, { id: "banana", label: "banana", children: [], parent: "root", start: 0, end: 5 }, { id: "anana", label: "anana", children: [], parent: "root", start: 1, end: 5 }], activeNode: "anana", pattern: "ana", matches: [], explanation: "Second suffix: 'anana' (indices 1-5). No common prefix with existing 'banana', so create new branch from root. Tree now has branches for 'b' and 'a'.", theoryConnection: "Without compression, tree has O(n²) nodes (sum of all suffix lengths). Example: 'aaaaa' would have n + (n-1) + ... + 1 = O(n²) edges. Need path compression: store edge labels as (start, end) pairs referencing original text.", complexity: "Space without compression: O(n²). With compression: O(n)." },
  { step: 3, title: "Add Suffix: nana", description: "Insert third suffix 'nana' starting at index 2.", codeLines: [4, 5, 6], text: "banana", nodes: [{ id: "root", label: "root", children: ["banana", "anana", "nana"], parent: null, start: 0, end: 0 }, { id: "banana", label: "banana", children: [], parent: "root", start: 0, end: 5 }, { id: "anana", label: "anana", children: [], parent: "root", start: 1, end: 5 }, { id: "nana", label: "nana", children: [], parent: "root", start: 2, end: 5 }], activeNode: "nana", pattern: "ana", matches: [], explanation: "Third suffix: 'nana' (indices 2-5). Creates third branch from root starting with 'n'. Suffixes are becoming shorter as we progress through the text.", theoryConnection: "Ukkonen's algorithm builds suffix tree online (left-to-right) in O(n). Uses suffix links to speed up traversal. Key insight: if we have suffix tree for text[0..i], we can extend it for text[0..i+1] efficiently.", complexity: "Ukkonen's: O(n) construction. Suffix links enable O(1) amortized per extension." },
  { step: 4, title: "Add Suffix: ana", description: "Insert fourth suffix 'ana' starting at index 3.", codeLines: [4, 5, 6], text: "banana", nodes: [{ id: "root", label: "root", children: ["banana", "anana", "nana", "ana"], parent: null, start: 0, end: 0 }, { id: "banana", label: "banana", children: [], parent: "root", start: 0, end: 5 }, { id: "anana", label: "anana", children: ["na"], parent: "root", start: 1, end: 5 }, { id: "nana", label: "nana", children: [], parent: "root", start: 2, end: 5 }, { id: "ana", label: "ana", children: [], parent: "anana", start: 3, end: 5 }], activeNode: "ana", pattern: "ana", matches: [1, 3], explanation: "Fourth suffix: 'ana' (indices 3-5). Shares prefix 'ana' with existing 'anana'! Split 'anana' at 'ana', create internal node, add 'na' as second branch. Now 'ana' appears at positions 1 and 3.", theoryConnection: "Internal nodes represent repeated substrings. 'ana' appears twice - at positions 1 and 3. Longest repeated substring = deepest internal node. Path compression crucial: store (start, end) indices, not actual substrings.", complexity: "Splitting: O(1) with proper data structures. Tree height: O(n) worst case, but compression keeps it manageable." },
  { step: 5, title: "Search Pattern: ana", description: "Traverse tree following 'ana' to find all occurrences.", codeLines: [12, 13, 14, 15, 16, 17], text: "banana", nodes: [{ id: "root", label: "root", children: ["banana", "anana", "nana"], parent: null, start: 0, end: 0 }, { id: "banana", label: "banana", children: [], parent: "root", start: 0, end: 5 }, { id: "anana", label: "anana", children: ["na"], parent: "root", start: 1, end: 5 }, { id: "ana", label: "ana", children: [], parent: "anana", start: 3, end: 5 }], activeNode: "ana", pattern: "ana", matches: [1, 3], explanation: "Pattern search 'ana': Start at root. Follow 'a' → 'anana' node. Continue 'n' → 'a' → found internal node. All leaves under this node are matches: positions 1 ('anana') and 3 ('ana'). Pattern appears twice!", theoryConnection: "Search complexity O(m) - independent of text size n! Huge advantage over linear search O(n×m). Works because suffix tree compresses all suffixes. Each comparison can skip multiple characters using edge labels.", complexity: "Search: O(m) where m = pattern length. Collecting all matches: O(occurrences)." },
  { step: 6, title: "Applications", description: "What suffix trees enable beyond simple search.", codeLines: [1, 2], text: "banana", nodes: [{ id: "root", label: "root", children: ["banana", "anana", "nana"], parent: null, start: 0, end: 0 }], activeNode: null, pattern: "", matches: [], explanation: "1. Longest Repeated Substring: deepest internal node ('ana' length 3). 2. Longest Common Substring: build generalized suffix tree for multiple strings. 3. Palindrome: longest suffix that's also prefix. 4. Pattern matching with wildcards. 5. DNA sequence analysis (find repeats, motifs).", theoryConnection: "Suffix array + LCP (Longest Common Prefix) array can replace suffix tree with less space (4n bytes vs ~20n bytes). Suffix tree edges can be binary searched for O(m log σ) search. Most modern systems use suffix arrays for space efficiency.", complexity: "Suffix array construction: O(n log n) or O(n) with skew algorithm. Space: 4n bytes for array + 4n for LCP." },
];

export default function SuffixTreeVisualizerEnhanced() {
  const { currentStep: stepIndex, totalSteps, isPlaying, playbackSpeed, togglePlay, pause, setStep, nextStep, prevStep, setTotalSteps, setPlaybackSpeed } = useTimeline();
  
  const [currentStep, setCurrentStep] = useState(0);

  useEffect(() => { setTotalSteps(generateSteps().length); }, [setTotalSteps]);
  useEffect(() => { setCurrentStep(stepIndex); }, [stepIndex]);
  const steps = generateSteps();
  const step = steps[currentStep] || steps[0];
  useEffect(() => { if (step?.codeLines) setActiveLines(step.codeLines); }, [step]);
  useEffect(() => { let interval: NodeJS.Timeout; if (isPlaying && currentStep < steps.length - 1) { interval = setInterval(() => nextStep(), 2500 / playbackSpeed); } else if (currentStep >= steps.length - 1 && isPlaying) pause(); return () => clearInterval(interval); }, [isPlaying, currentStep, steps.length, playbackSpeed, nextStep, pause]);
  const handleReset = useCallback(() => { pause(); setStep(0); }, [pause, setStep]);

  return (
    <div className="w-full h-full flex flex-col bg-[#0d1117] rounded-lg overflow-hidden">
      <div className="flex items-center justify-between p-4 border-b border-[#30363d] bg-[#161b22]">
        <div><h3 className="text-white font-semibold text-lg">Suffix Trees</h3><p className="text-[#8b949e] text-sm">All Suffixes | O(m) Pattern Search | LCS</p></div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 px-3 py-1 bg-[#21262d] rounded-lg"><Search size={14} className="text-[#58a6ff]" /><span className="text-[#8b949e] text-xs">Text:</span><span className="text-[#f0883e] font-bold">{step.text}</span></div>
          <div className="w-32 h-2 bg-[#21262d] rounded-full"><div className="h-full bg-[#58a6ff] rounded-full transition-all" style={{ width: `${((currentStep + 1) / steps.length) * 100}%` }} /></div>
        </div>
      </div>
      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 flex flex-col p-6">
          <div className="mb-4 flex gap-2">{step.text.split('').map((c, i) => (<div key={i} className={`w-10 h-10 rounded-lg flex items-center justify-center font-bold ${step.matches.includes(i) ? "bg-[#3fb950] text-white" : "bg-[#21262d] text-[#c9d1d9]"}`}><span className="text-[#6e7681] text-xs absolute -mt-7">{i}</span>{c}</div>))}</div>
          <div className="flex-1 bg-[#161b22] rounded-lg p-4 relative">
            <div className="text-center mb-2 text-[#8b949e] text-sm">Suffix Tree Structure</div>
            <div className="flex flex-col items-center gap-4">
              <motion.div className={`px-4 py-2 rounded-lg border-2 ${step.activeNode === "root" ? "border-[#f0883e] bg-[#f0883e]/20" : "border-[#58a6ff] bg-[#58a6ff]/20"}`}><span className="text-white font-medium">root</span></motion.div>
              <div className="flex gap-8">{step.nodes.filter(n => n.parent === "root").map(n => (<div key={n.id} className="flex flex-col items-center gap-2"><div className="w-px h-8 bg-[#30363d]" /><motion.div className={`px-3 py-1 rounded-lg border-2 ${step.activeNode === n.id ? "border-[#f0883e] bg-[#f0883e]/20" : "border-[#3fb950] bg-[#3fb950]/10"}`}><span className="text-[#c9d1d9] text-sm">{n.label}</span></motion.div></div>))}</div>
            </div>
          </div>
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Text Length</span><p className="text-white font-bold text-lg">{step.text.length}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Pattern</span><p className="text-[#f0883e] font-bold text-lg">{step.pattern || "-"}</p></div>
            <div className="p-3 bg-[#21262d] rounded-lg border border-[#30363d]"><span className="text-[#8b949e] text-xs">Matches</span><p className="text-[#3fb950] font-bold text-lg">{step.matches.length}</p></div>
          </div>
        </div>
        <div className="w-96 border-l border-[#30363d] bg-[#161b22] flex flex-col">
          <div className="p-5 border-b border-[#30363d]"><span className="text-[#58a6ff] text-xs font-mono uppercase tracking-wider">Step {currentStep + 1}: {step.title}</span><p className="text-[#c9d1d9] mt-3 leading-relaxed">{step.description}</p></div>
          <div className="p-5 border-b border-[#30363d] flex-1 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">What is Happening</h4><p className="text-[#c9d1d9] text-sm leading-relaxed mb-4">{step.explanation}</p><div className="mt-4 p-3 bg-[#238636]/10 border border-[#238636]/30 rounded-lg"><h4 className="text-[#3fb950] text-xs uppercase tracking-wider mb-1">💡 Theory Connection</h4><p className="text-[#c9d1d9] text-sm leading-relaxed">{step.theoryConnection}</p></div><div className="mt-4 p-3 bg-[#58a6ff]/10 border border-[#58a6ff]/30 rounded-lg"><h4 className="text-[#58a6ff] text-xs uppercase tracking-wider mb-1">⏱️ Complexity</h4><p className="text-[#c9d1d9] text-sm font-mono">{step.complexity}</p></div></div>
          <div className="p-4 bg-[#0d1117] max-h-56 overflow-y-auto"><h4 className="text-[#8b949e] text-xs uppercase tracking-wider mb-2">Code Reference</h4><div className="text-xs font-mono">{codeLines.map((line, i) => (<div key={i} className={`px-2 py-0.5 rounded ${step.codeLines?.includes(i + 1) ? "bg-[#238636]/30 text-[#7ee787] border-l-2 border-[#238636]" : "text-[#8b949e]"}`}><span className="text-[#6e7681] w-6 inline-block select-none">{i + 1}</span>{line || " "}</div>))}</div></div>
        </div>
      </div>
      <div className="p-4 border-t border-[#30363d] bg-[#161b22]">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2"><button onClick={() => { pause(); setStep(0); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipBack size={18} /></button><button onClick={prevStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronLeft size={20} /></button><button onClick={togglePlay} className="px-6 py-2 bg-[#238636] hover:bg-[#2ea043] text-white rounded-lg font-medium flex items-center gap-2">{isPlaying ? <Pause size={18} /> : <Play size={18} />}{isPlaying ? "Pause" : "Play"}</button><button onClick={nextStep} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><ChevronRight size={20} /></button><button onClick={() => { pause(); setStep(steps.length - 1); }} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><SkipForward size={18} /></button><button onClick={handleReset} className="p-2 rounded-lg hover:bg-[#21262d] text-[#8b949e] hover:text-white"><RotateCcw size={18} /></button></div>
          <div className="flex items-center gap-3"><span className="text-[#8b949e] text-sm">Speed:</span><div className="flex gap-1">{speeds.map(s => <button key={s.value} onClick={() => setPlaybackSpeed(s.value)} className={`px-2 py-1 rounded text-xs font-medium ${playbackSpeed === s.value ? "bg-[#58a6ff] text-white" : "bg-[#21262d] text-[#8b949e]"}`}>{s.label}</button>)}</div></div>
        </div>
      </div>
    </div>
  );
}
